"""create asset table

Revision ID: 0dab7d02517c
Revises: 6cbb91c6dd1f
Create Date: 2026-05-11 12:43:10.436824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dab7d02517c'
down_revision: Union[str, None] = '6cbb91c6dd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('serialNumber', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('purchaseDate', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('condition', sa.String(length=40), server_default='GOOD', nullable=False),
    sa.Column('status', sa.String(length=40), server_default='AVAILABLE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_organizationId_category_idx', 'asset', ['organizationId', 'category'], unique=False)
    op.create_index('asset_organizationId_deletedAt_idx', 'asset', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('asset_organizationId_idx', 'asset', ['organizationId'], unique=False)
    op.create_index('asset_organizationId_status_idx', 'asset', ['organizationId', 'status'], unique=False)
    op.create_table('asset_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('assignedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('assignedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expectedReturnDate', sa.Date(), nullable=True),
    sa.Column('returnedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conditionOnReturn', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_assignment_assetId_idx', 'asset_assignment', ['assetId'], unique=False)
    op.create_index('asset_assignment_expectedReturnDate_idx', 'asset_assignment', ['expectedReturnDate'], unique=False)
    op.create_index('asset_assignment_memberId_idx', 'asset_assignment', ['memberId'], unique=False)
    op.create_table('asset_maintenance_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('loggedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('maintenanceType', sa.String(length=40), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('assetCondition', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('loggedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['loggedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_maintenance_log_assetId_idx', 'asset_maintenance_log', ['assetId'], unique=False)
    op.create_index('asset_maintenance_log_loggedAt_idx', 'asset_maintenance_log', ['loggedAt'], unique=False)
    op.drop_index(op.f('ix_stage_event_googleCalendarEventId'), table_name='stage_event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stage_event_googleCalendarEventId'), 'stage_event', ['googleCalendarEventId'], unique=False)
    op.drop_index('asset_maintenance_log_loggedAt_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_assetId_idx', table_name='asset_maintenance_log')
    op.drop_table('asset_maintenance_log')
    op.drop_index('asset_assignment_memberId_idx', table_name='asset_assignment')
    op.drop_index('asset_assignment_expectedReturnDate_idx', table_name='asset_assignment')
    op.drop_index('asset_assignment_assetId_idx', table_name='asset_assignment')
    op.drop_table('asset_assignment')
    op.drop_index('asset_organizationId_status_idx', table_name='asset')
    op.drop_index('asset_organizationId_idx', table_name='asset')
    op.drop_index('asset_organizationId_deletedAt_idx', table_name='asset')
    op.drop_index('asset_organizationId_category_idx', table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
