"""add stage events and offer letters

Revision ID: 258a8b4eb1d5
Revises: f41f4e7cb3c6
Create Date: 2026-05-08 08:36:52.424818
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258a8b4eb1d5'
down_revision: Union[str, None] = 'f41f4e7cb3c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_letter',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'WITHDRAWN', name='offerstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('joiningDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respondedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidateToken', sa.String(), nullable=True),
    sa.Column('pdfUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidateToken')
    )
    op.create_index(op.f('ix_offer_letter_applicationId'), 'offer_letter', ['applicationId'], unique=True)
    op.create_index(op.f('ix_offer_letter_createdByMemberId'), 'offer_letter', ['createdByMemberId'], unique=False)
    op.create_index(op.f('ix_offer_letter_organizationId'), 'offer_letter', ['organizationId'], unique=False)
    op.create_index(op.f('ix_offer_letter_status'), 'offer_letter', ['status'], unique=False)
    op.create_table('stage_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interviewType', sa.Enum('SCREENING', 'TECHNICAL', 'CULTURAL', 'MANAGERIAL', 'HR', 'FINAL', 'OTHER', name='interviewtype'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='eventstatus'), nullable=False),
    sa.Column('scheduledStartAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduledEndAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meetingUrl', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_event_applicationId'), 'stage_event', ['applicationId'], unique=False)
    op.create_index(op.f('ix_stage_event_createdByMemberId'), 'stage_event', ['createdByMemberId'], unique=False)
    op.create_index(op.f('ix_stage_event_organizationId'), 'stage_event', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_event_stageId'), 'stage_event', ['stageId'], unique=False)
    op.create_index(op.f('ix_stage_event_status'), 'stage_event', ['status'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'STRONG_YES', 'YES', 'NEUTRAL', 'NO', 'STRONG_NO', name='interviewoutcome'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_interview_feedback_event_member')
    )
    op.create_index(op.f('ix_interview_feedback_eventId'), 'interview_feedback', ['eventId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_memberId'), 'interview_feedback', ['memberId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_organizationId'), 'interview_feedback', ['organizationId'], unique=False)
    op.create_table('stage_event_participant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_stage_event_participant')
    )
    op.create_index(op.f('ix_stage_event_participant_eventId'), 'stage_event_participant', ['eventId'], unique=False)
    op.create_index(op.f('ix_stage_event_participant_memberId'), 'stage_event_participant', ['memberId'], unique=False)
    stage_type_enum = sa.Enum(
        'DEFAULT',
        'INTERVIEW',
        'OFFER',
        'HIRED',
        'REJECTED',
        name='stagetype'
    )

    stage_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'pipeline_stage',
        sa.Column(
            'stageType',
            stage_type_enum,
            nullable=False,
            server_default='DEFAULT',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_stage', 'stageType')
    op.drop_index(op.f('ix_stage_event_participant_memberId'), table_name='stage_event_participant')
    op.drop_index(op.f('ix_stage_event_participant_eventId'), table_name='stage_event_participant')
    op.drop_table('stage_event_participant')
    op.drop_index(op.f('ix_interview_feedback_organizationId'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_memberId'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_eventId'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_stage_event_status'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_stageId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_organizationId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_createdByMemberId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_applicationId'), table_name='stage_event')
    op.drop_table('stage_event')
    op.drop_index(op.f('ix_offer_letter_status'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_organizationId'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_createdByMemberId'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_applicationId'), table_name='offer_letter')
    op.drop_table('offer_letter')
    # ### end Alembic commands ###
