"""sync_with_prisma_baseline

Revision ID: 333100a8dc1a
Revises: 
Create Date: 2026-05-26 16:07:26.145939
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '333100a8dc1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('assetCode', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('categoryDefinitionId', sa.String(length=36), nullable=True),
    sa.Column('serialNumber', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('purchaseDate', sa.Date(), nullable=True),
    sa.Column('purchasePrice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('warrantyExpiryDate', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=40), server_default='GOOD', nullable=False),
    sa.Column('status', sa.String(length=40), server_default='AVAILABLE', nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_organizationId_assetCode_idx', 'asset', ['organizationId', 'assetCode'], unique=False)
    op.create_index('asset_organizationId_category_idx', 'asset', ['organizationId', 'category'], unique=False)
    op.create_index('asset_organizationId_deletedAt_idx', 'asset', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('asset_organizationId_idx', 'asset', ['organizationId'], unique=False)
    op.create_index('asset_organizationId_status_idx', 'asset', ['organizationId', 'status'], unique=False)
    op.create_table('asset_category_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_code', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_category_def_org_idx', 'asset_category_definition', ['organizationId'], unique=False)
    op.create_index('asset_category_def_org_name_idx', 'asset_category_definition', ['organizationId', 'name'], unique=False)
    op.create_table('attendanceRecord',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clockIn', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clockOut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projectId', sa.String(length=36), nullable=True),
    sa.Column('projectTaskId', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('totalHours', sa.Float(), nullable=True),
    sa.Column('overtimeHours', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='ABSENT', nullable=False),
    sa.Column('enteredByManagerId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employeeId', 'date', name='attendanceRecord_employeeId_date_key')
    )
    op.create_index('attendanceRecord_organizationId_date_idx', 'attendanceRecord', ['organizationId', 'date'], unique=False)
    op.create_index('attendanceRecord_organizationId_employeeId_idx', 'attendanceRecord', ['organizationId', 'employeeId'], unique=False)
    op.create_index('attendanceRecord_organizationId_idx', 'attendanceRecord', ['organizationId'], unique=False)
    op.create_index('attendanceRecord_projectId_idx', 'attendanceRecord', ['projectId'], unique=False)
    op.create_index('attendanceRecord_projectTaskId_idx', 'attendanceRecord', ['projectTaskId'], unique=False)
    op.create_table('holiday',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('holidayDate', sa.Date(), nullable=False),
    sa.Column('isHoliday', sa.Boolean(), nullable=False),
    sa.Column('isRecurring', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('holiday_organizationId_deletedAt_idx', 'holiday', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('holiday_organizationId_holidayDate_idx', 'holiday', ['organizationId', 'holidayDate'], unique=False)
    op.create_index('holiday_organizationId_idx', 'holiday', ['organizationId'], unique=False)
    op.create_table('leave_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quota', sa.Float(), nullable=False),
    sa.Column('carryForward', sa.Boolean(), nullable=False),
    sa.Column('isPaid', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'name', name='leave_type_organizationId_name_key')
    )
    op.create_index('leave_type_organizationId_deletedAt_idx', 'leave_type', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('leave_type_organizationId_idx', 'leave_type', ['organizationId'], unique=False)
    op.create_table('monthly_plans',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_location', sa.String(length=40), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'date', name='uq_monthly_plan_org_user_date')
    )
    op.create_index(op.f('ix_monthly_plans_organization_id'), 'monthly_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_monthly_plans_user_id'), 'monthly_plans', ['user_id'], unique=False)
    op.create_table('public_holiday_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), server_default='IN-TN', nullable=False),
    sa.Column('isHoliday', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'name', 'location', name='public_holiday_master_date_name_location_key')
    )
    op.create_index('public_holiday_master_year_location_idx', 'public_holiday_master', ['year', 'location'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_location', sa.String(length=40), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'date', name='uq_weekly_plan_org_user_date')
    )
    op.create_index(op.f('ix_weekly_plans_organization_id'), 'weekly_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_table('workHourPolicy',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('standardHoursPerDay', sa.Float(), server_default='8', nullable=False),
    sa.Column('overtimeThreshold', sa.Float(), server_default='8', nullable=False),
    sa.Column('lateThresholdMinutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('workStartHour', sa.Integer(), server_default='9', nullable=False),
    sa.Column('workStartMinute', sa.Integer(), server_default='0', nullable=False),
    sa.Column('halfDayMaxHours', sa.Float(), server_default='4', nullable=False),
    sa.Column('absentAfterHour', sa.Integer(), server_default='18', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', name='workHourPolicy_organizationId_key')
    )
    op.create_table('asset_category_field_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('categoryId', sa.String(length=36), nullable=False),
    sa.Column('fieldName', sa.String(length=100), nullable=False),
    sa.Column('fieldType', sa.String(length=20), nullable=False),
    sa.Column('fieldOptions', sa.JSON(), nullable=True),
    sa.Column('isRequired', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('displayOrder', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['asset_category_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_cat_field_def_cat_idx', 'asset_category_field_definition', ['categoryId'], unique=False)
    op.create_table('asset_id_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('assetIdName', sa.String(length=120), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id_definitions_organizationId'), 'asset_id_definitions', ['organizationId'], unique=False)
    op.create_table('attendanceWorkLog',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attendanceRecordId', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('employeeId', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('projectId', sa.String(length=36), nullable=True),
    sa.Column('projectTaskId', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendanceRecordId'], ['attendanceRecord.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('attendanceWorkLog_attendanceRecordId_idx', 'attendanceWorkLog', ['attendanceRecordId'], unique=False)
    op.create_index('attendanceWorkLog_organizationId_date_idx', 'attendanceWorkLog', ['organizationId', 'date'], unique=False)
    op.create_index('attendanceWorkLog_organizationId_employeeId_idx', 'attendanceWorkLog', ['organizationId', 'employeeId'], unique=False)
    op.create_index('attendanceWorkLog_organizationId_idx', 'attendanceWorkLog', ['organizationId'], unique=False)
    op.create_index('attendanceWorkLog_projectId_idx', 'attendanceWorkLog', ['projectId'], unique=False)
    op.create_index('attendanceWorkLog_projectTaskId_idx', 'attendanceWorkLog', ['projectTaskId'], unique=False)
    op.create_table('candidate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linkedinUrl', sa.String(), nullable=True),
    sa.Column('portfolioUrl', sa.String(), nullable=True),
    sa.Column('currentCompany', sa.String(), nullable=True),
    sa.Column('currentTitle', sa.String(), nullable=True),
    sa.Column('totalExperience', sa.String(), nullable=True),
    sa.Column('resumeUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'email', name='uq_candidate_org_email')
    )
    op.create_index(op.f('ix_candidate_organizationId'), 'candidate', ['organizationId'], unique=False)
    op.create_table('asset_custom_field_value',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('fieldDefinitionId', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fieldDefinitionId'], ['asset_category_field_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_custom_field_asset_def_idx', 'asset_custom_field_value', ['assetId', 'fieldDefinitionId'], unique=True)
    op.create_index('asset_custom_field_asset_idx', 'asset_custom_field_value', ['assetId'], unique=False)
    op.create_index('asset_custom_field_def_idx', 'asset_custom_field_value', ['fieldDefinitionId'], unique=False)
    op.create_table('asset_unit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('serialNumber', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='AVAILABLE', nullable=False),
    sa.Column('currentHolderMemberId', sa.String(length=36), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currentHolderMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_unit_asset_idx', 'asset_unit', ['assetId'], unique=False)
    op.create_index('asset_unit_holder_idx', 'asset_unit', ['currentHolderMemberId'], unique=False)
    op.create_index('asset_unit_status_idx', 'asset_unit', ['status'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parentDepartmentId', sa.String(length=36), nullable=True),
    sa.Column('headMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='ACTIVE', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['headMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parentDepartmentId'], ['department.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('department_headMemberId_idx', 'department', ['headMemberId'], unique=False)
    op.create_index('department_organizationId_idx', 'department', ['organizationId'], unique=False)
    op.create_index('department_organizationId_status_idx', 'department', ['organizationId', 'status'], unique=False)
    op.create_index('department_parentDepartmentId_idx', 'department', ['parentDepartmentId'], unique=False)
    op.create_table('leave_balance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('leaveTypeId', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('carriedForward', sa.Float(), nullable=False),
    sa.Column('lapsed', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leaveTypeId'], ['leave_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'memberId', 'leaveTypeId', 'year', name='leave_balance_org_member_type_year_key')
    )
    op.create_index('leave_balance_organizationId_idx', 'leave_balance', ['organizationId'], unique=False)
    op.create_index('leave_balance_organizationId_leaveTypeId_year_idx', 'leave_balance', ['organizationId', 'leaveTypeId', 'year'], unique=False)
    op.create_index('leave_balance_organizationId_memberId_year_idx', 'leave_balance', ['organizationId', 'memberId', 'year'], unique=False)
    op.create_table('leave_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('leaveTypeId', sa.String(length=36), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approvedById', sa.String(length=36), nullable=True),
    sa.Column('approverComment', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelledAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approvedById'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leaveTypeId'], ['leave_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('leave_request_approvedById_idx', 'leave_request', ['approvedById'], unique=False)
    op.create_index('leave_request_organizationId_idx', 'leave_request', ['organizationId'], unique=False)
    op.create_index('leave_request_organizationId_leaveTypeId_idx', 'leave_request', ['organizationId', 'leaveTypeId'], unique=False)
    op.create_index('leave_request_organizationId_memberId_idx', 'leave_request', ['organizationId', 'memberId'], unique=False)
    op.create_index('leave_request_organizationId_startDate_endDate_idx', 'leave_request', ['organizationId', 'startDate', 'endDate'], unique=False)
    op.create_index('leave_request_organizationId_startDate_idx', 'leave_request', ['organizationId', 'startDate'], unique=False)
    op.create_index('leave_request_organizationId_status_idx', 'leave_request', ['organizationId', 'status'], unique=False)
    op.create_table('asset_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('assetUnitId', sa.String(length=36), nullable=True),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('providedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('providedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('conditionWhileProviding', sa.String(length=40), nullable=False),
    sa.Column('provideNotes', sa.Text(), nullable=True),
    sa.Column('returnDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returnedCondition', sa.String(length=40), nullable=True),
    sa.Column('receivedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('returnNotes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assetUnitId'], ['asset_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['providedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receivedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_assignment_assetId_idx', 'asset_assignment', ['assetId'], unique=False)
    op.create_index('asset_assignment_memberId_idx', 'asset_assignment', ['memberId'], unique=False)
    op.create_index('asset_assignment_returnDate_idx', 'asset_assignment', ['returnDate'], unique=False)
    op.create_table('asset_maintenance_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticketId', sa.String(length=7), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('ticketMode', sa.String(length=40), server_default='ASSET_ISSUE', nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=True),
    sa.Column('assetUnitId', sa.String(length=36), nullable=True),
    sa.Column('loggedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=True),
    sa.Column('attachmentsMetadata', sa.JSON(), nullable=True),
    sa.Column('maintenanceType', sa.String(length=40), nullable=False),
    sa.Column('issueDescription', sa.Text(), nullable=False),
    sa.Column('serviceDate', sa.Date(), nullable=False),
    sa.Column('expectedCompletionDate', sa.Date(), nullable=True),
    sa.Column('completedDate', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='OPEN', nullable=False),
    sa.Column('conditionBeforeMaintenance', sa.String(length=40), nullable=True),
    sa.Column('conditionAfterMaintenance', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assetUnitId'], ['asset_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loggedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_maintenance_log_assetId_idx', 'asset_maintenance_log', ['assetId'], unique=False)
    op.create_index('asset_maintenance_log_category_idx', 'asset_maintenance_log', ['category'], unique=False)
    op.create_index('asset_maintenance_log_organizationId_idx', 'asset_maintenance_log', ['organizationId'], unique=False)
    op.create_index('asset_maintenance_log_serviceDate_idx', 'asset_maintenance_log', ['serviceDate'], unique=False)
    op.create_index('asset_maintenance_log_status_idx', 'asset_maintenance_log', ['status'], unique=False)
    op.create_index('asset_maintenance_log_ticketId_key', 'asset_maintenance_log', ['ticketId'], unique=True)
    op.create_index('asset_maintenance_log_ticketMode_idx', 'asset_maintenance_log', ['ticketMode'], unique=False)
    op.create_table('departmentMember',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('joinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departmentId', 'memberId', name='departmentMember_departmentId_memberId_key')
    )
    op.create_index('departmentMember_departmentId_idx', 'departmentMember', ['departmentId'], unique=False)
    op.create_index('departmentMember_memberId_idx', 'departmentMember', ['memberId'], unique=False)
    op.create_table('job_requisition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=True),
    sa.Column('employmentType', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employmenttype'), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('salaryMin', sa.Float(), nullable=True),
    sa.Column('salaryMax', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('isRemote', sa.Boolean(), nullable=False),
    sa.Column('raisedById', sa.String(length=36), nullable=False),
    sa.Column('targetDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hiringReason', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('replacementForId', sa.String(length=36), nullable=True),
    sa.Column('businessJustification', sa.Text(), nullable=True),
    sa.Column('salaryVisibility', sa.String(), nullable=False),
    sa.Column('experienceLevel', sa.String(), nullable=True),
    sa.Column('minExperience', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('certifications', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('knockoutRule', sa.Text(), nullable=True),
    sa.Column('roleSummary', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('requirementsRich', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('aboutTeam', sa.Text(), nullable=True),
    sa.Column('requisitionNumber', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PENDING', 'PENDING_APPROVAL', 'PARTIALLY_APPROVED', 'APPROVED', 'REJECTED', 'PUBLISHED', 'ACTIVE_HIRING', 'FILLED', 'CLOSED', 'ARCHIVED', name='jobrequisitionstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raisedById'], ['member.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replacementForId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requisition_departmentId'), 'job_requisition', ['departmentId'], unique=False)
    op.create_index('ix_job_requisition_org_raised_by', 'job_requisition', ['organizationId', 'raisedById'], unique=False)
    op.create_index('ix_job_requisition_org_replacement', 'job_requisition', ['organizationId', 'replacementForId'], unique=False)
    op.create_index('ix_job_requisition_org_status', 'job_requisition', ['organizationId', 'status'], unique=False)
    op.create_index(op.f('ix_job_requisition_organizationId'), 'job_requisition', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_requisition_raisedById'), 'job_requisition', ['raisedById'], unique=False)
    op.create_index(op.f('ix_job_requisition_replacementForId'), 'job_requisition', ['replacementForId'], unique=False)
    op.create_index(op.f('ix_job_requisition_status'), 'job_requisition', ['status'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leadMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leadMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'departmentId', 'name', name='team_organizationId_departmentId_name_key')
    )
    op.create_index('team_departmentId_idx', 'team', ['departmentId'], unique=False)
    op.create_index('team_leadMemberId_idx', 'team', ['leadMemberId'], unique=False)
    op.create_index('team_organizationId_idx', 'team', ['organizationId'], unique=False)
    op.create_index('team_organizationId_status_idx', 'team', ['organizationId', 'status'], unique=False)
    op.create_table('job_posting',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='jobpostingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('publishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'slug', name='uq_job_posting_org_slug')
    )
    op.create_index(op.f('ix_job_posting_organizationId'), 'job_posting', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_posting_requisitionId'), 'job_posting', ['requisitionId'], unique=False)
    op.create_index(op.f('ix_job_posting_status'), 'job_posting', ['status'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clientName', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budgetedHours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_organizationId_deletedAt_idx', 'project', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('project_organizationId_idx', 'project', ['organizationId'], unique=False)
    op.create_index('project_organizationId_status_idx', 'project', ['organizationId', 'status'], unique=False)
    op.create_index('project_teamId_idx', 'project', ['teamId'], unique=False)
    op.create_table('requisition_activity_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=False),
    sa.Column('actorId', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('fieldChanges', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actorId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisition_activity_log_action'), 'requisition_activity_log', ['action'], unique=False)
    op.create_index(op.f('ix_requisition_activity_log_actorId'), 'requisition_activity_log', ['actorId'], unique=False)
    op.create_index(op.f('ix_requisition_activity_log_createdAt'), 'requisition_activity_log', ['createdAt'], unique=False)
    op.create_index('ix_requisition_activity_log_org_action', 'requisition_activity_log', ['organizationId', 'action'], unique=False)
    op.create_index(op.f('ix_requisition_activity_log_organizationId'), 'requisition_activity_log', ['organizationId'], unique=False)
    op.create_index(op.f('ix_requisition_activity_log_requisitionId'), 'requisition_activity_log', ['requisitionId'], unique=False)
    op.create_table('requisition_approval',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=False),
    sa.Column('approverId', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requisitionapprovaldecision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decidedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approverId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisitionId', 'approverId', name='uq_requisition_approval_requisition_approver')
    )
    op.create_index(op.f('ix_requisition_approval_approverId'), 'requisition_approval', ['approverId'], unique=False)
    op.create_index(op.f('ix_requisition_approval_decision'), 'requisition_approval', ['decision'], unique=False)
    op.create_index(op.f('ix_requisition_approval_organizationId'), 'requisition_approval', ['organizationId'], unique=False)
    op.create_index(op.f('ix_requisition_approval_requisitionId'), 'requisition_approval', ['requisitionId'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('joinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'memberId', name='team_member_teamId_memberId_key')
    )
    op.create_index('team_member_memberId_idx', 'team_member', ['memberId'], unique=False)
    op.create_index('team_member_teamId_idx', 'team_member', ['teamId'], unique=False)
    op.create_table('job_requisition_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=True),
    sa.Column('rulesVersion', sa.String(length=20), nullable=False),
    sa.Column('knockoutRules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoringWeights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sourceSnapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'requisitionId', name='uq_job_requisition_rules_org_requisition')
    )
    op.create_index(op.f('ix_job_requisition_rules_jobPostingId'), 'job_requisition_rules', ['jobPostingId'], unique=False)
    op.create_index('ix_job_requisition_rules_org_posting', 'job_requisition_rules', ['organizationId', 'jobPostingId'], unique=False)
    op.create_index('ix_job_requisition_rules_org_requisition', 'job_requisition_rules', ['organizationId', 'requisitionId'], unique=False)
    op.create_index(op.f('ix_job_requisition_rules_organizationId'), 'job_requisition_rules', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_requisition_rules_requisitionId'), 'job_requisition_rules', ['requisitionId'], unique=True)
    op.create_table('pipeline_stage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('isDefault', sa.Boolean(), nullable=False),
    sa.Column('isFinal', sa.Boolean(), nullable=False),
    sa.Column('stageType', sa.Enum('DEFAULT', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='stagetype'), nullable=False),
    sa.Column('meetingEnabled', sa.Boolean(), nullable=False),
    sa.Column('offerLetterEnabled', sa.Boolean(), nullable=False),
    sa.Column('evaluationEnabled', sa.Boolean(), nullable=False),
    sa.Column('sheetEnabled', sa.Boolean(), nullable=False),
    sa.Column('evaluationType', sa.String(length=32), nullable=True),
    sa.Column('evaluationIncludeTotal', sa.Boolean(), nullable=False),
    sa.Column('evaluationIncludeAnalysis', sa.Boolean(), nullable=False),
    sa.Column('dueDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extendToNextWorkingDay', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobPostingId', 'order', name='uq_pipeline_stage_order'),
    sa.UniqueConstraint('jobPostingId', 'slug', name='uq_pipeline_stage_job_slug')
    )
    op.create_index(op.f('ix_pipeline_stage_jobPostingId'), 'pipeline_stage', ['jobPostingId'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_organizationId'), 'pipeline_stage', ['organizationId'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_stageId'), 'pipeline_stage', ['stageId'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('allocatedHours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId', 'memberId', name='project_member_projectId_memberId_key')
    )
    op.create_index('project_member_memberId_idx', 'project_member', ['memberId'], unique=False)
    op.create_index('project_member_projectId_idx', 'project_member', ['projectId'], unique=False)
    op.create_table('project_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_task_projectId_idx', 'project_task', ['projectId'], unique=False)
    op.create_table('candidate_application',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('candidateId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=False),
    sa.Column('pipelineStageId', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('LINKEDIN', 'REFERRAL', 'COMPANY_WEBSITE', 'JOB_BOARD', 'DIRECT', 'OTHER', name='applicationsource'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internalNotes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('appliedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastActivityAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipelineStageId'], ['pipeline_stage.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidateId', 'jobPostingId', name='uq_candidate_job_application')
    )
    op.create_index(op.f('ix_candidate_application_jobPostingId'), 'candidate_application', ['jobPostingId'], unique=False)
    op.create_index('ix_candidate_application_org_stage', 'candidate_application', ['organizationId', 'pipelineStageId'], unique=False)
    op.create_index(op.f('ix_candidate_application_organizationId'), 'candidate_application', ['organizationId'], unique=False)
    op.create_index(op.f('ix_candidate_application_pipelineStageId'), 'candidate_application', ['pipelineStageId'], unique=False)
    op.create_table('hiring_team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hiring_team_jobPostingId_idx', 'hiring_team', ['jobPostingId'], unique=False)
    op.create_index('hiring_team_organizationId_idx', 'hiring_team', ['organizationId'], unique=False)
    op.create_index('hiring_team_organizationId_isActive_idx', 'hiring_team', ['organizationId', 'isActive'], unique=False)
    op.create_index(op.f('ix_hiring_team_jobPostingId'), 'hiring_team', ['jobPostingId'], unique=False)
    op.create_index(op.f('ix_hiring_team_organizationId'), 'hiring_team', ['organizationId'], unique=False)
    op.create_index(op.f('ix_hiring_team_stageId'), 'hiring_team', ['stageId'], unique=False)
    op.create_table('stage_evaluation_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('valueType', sa.String(length=32), nullable=False),
    sa.Column('maxScore', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stageId', 'order', name='uq_stage_evaluation_category_order')
    )
    op.create_index('ix_stage_evaluation_category_org_stage', 'stage_evaluation_category', ['organizationId', 'stageId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_category_organizationId'), 'stage_evaluation_category', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_category_stageId'), 'stage_evaluation_category', ['stageId'], unique=False)
    op.create_table('stage_evaluation_workspace',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=False),
    sa.Column('googleSpreadsheetId', sa.String(length=255), nullable=False),
    sa.Column('googleSpreadsheetUrl', sa.Text(), nullable=False),
    sa.Column('googleSheetId', sa.Integer(), nullable=True),
    sa.Column('googleSheetTitle', sa.String(length=100), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'stageId', name='uq_stage_evaluation_workspace_org_stage'),
    sa.UniqueConstraint('stageId', name='uq_stage_evaluation_workspace_stage')
    )
    op.create_index(op.f('ix_stage_evaluation_workspace_createdByMemberId'), 'stage_evaluation_workspace', ['createdByMemberId'], unique=False)
    op.create_index('ix_stage_evaluation_workspace_org_stage', 'stage_evaluation_workspace', ['organizationId', 'stageId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_workspace_organizationId'), 'stage_evaluation_workspace', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_workspace_stageId'), 'stage_evaluation_workspace', ['stageId'], unique=False)
    op.create_table('application_stage_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('fromStageId', sa.String(length=36), nullable=True),
    sa.Column('toStageId', sa.String(length=36), nullable=False),
    sa.Column('movedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fromStageId'], ['pipeline_stage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['toStageId'], ['pipeline_stage.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_stage_history_applicationId'), 'application_stage_history', ['applicationId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_fromStageId'), 'application_stage_history', ['fromStageId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_movedByMemberId'), 'application_stage_history', ['movedByMemberId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_organizationId'), 'application_stage_history', ['organizationId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_toStageId'), 'application_stage_history', ['toStageId'], unique=False)
    op.create_table('candidate_application_note',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('authorMemberId', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['authorMemberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_application_note_applicationId'), 'candidate_application_note', ['applicationId'], unique=False)
    op.create_index(op.f('ix_candidate_application_note_authorMemberId'), 'candidate_application_note', ['authorMemberId'], unique=False)
    op.create_index(op.f('ix_candidate_application_note_organizationId'), 'candidate_application_note', ['organizationId'], unique=False)
    op.create_index('ix_candidate_note_org_application', 'candidate_application_note', ['organizationId', 'applicationId'], unique=False)
    op.create_index('ix_candidate_note_org_author', 'candidate_application_note', ['organizationId', 'authorMemberId'], unique=False)
    op.create_table('candidate_resume_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resumeUrl', sa.Text(), nullable=True),
    sa.Column('resumeContentType', sa.String(length=255), nullable=True),
    sa.Column('resumeFileType', sa.String(length=20), nullable=True),
    sa.Column('resumeSizeBytes', sa.Integer(), nullable=True),
    sa.Column('firewallFlags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('removedSuspiciousText', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('isFlaggedForCheating', sa.Boolean(), nullable=False),
    sa.Column('extractedText', sa.Text(), nullable=True),
    sa.Column('sanitizedText', sa.Text(), nullable=True),
    sa.Column('parserWarnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extractedFacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compositeScore', sa.Integer(), nullable=True),
    sa.Column('rawScore', sa.Integer(), nullable=True),
    sa.Column('maxScore', sa.Integer(), nullable=True),
    sa.Column('evaluationStatus', sa.String(length=32), nullable=True),
    sa.Column('failedKnockouts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scoreBreakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extractionConfidence', sa.Float(), nullable=True),
    sa.Column('analysisVersion', sa.String(length=20), nullable=False),
    sa.Column('attemptCount', sa.Integer(), nullable=False),
    sa.Column('lastError', sa.Text(), nullable=True),
    sa.Column('analyzedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'applicationId', name='uq_candidate_resume_analysis_org_application')
    )
    op.create_index(op.f('ix_candidate_resume_analysis_applicationId'), 'candidate_resume_analysis', ['applicationId'], unique=True)
    op.create_index('ix_candidate_resume_analysis_org_application', 'candidate_resume_analysis', ['organizationId', 'applicationId'], unique=False)
    op.create_index('ix_candidate_resume_analysis_org_status', 'candidate_resume_analysis', ['organizationId', 'status'], unique=False)
    op.create_index(op.f('ix_candidate_resume_analysis_organizationId'), 'candidate_resume_analysis', ['organizationId'], unique=False)
    op.create_index(op.f('ix_candidate_resume_analysis_status'), 'candidate_resume_analysis', ['status'], unique=False)
    op.create_table('hiring_team_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hiringTeamId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hiringTeamId'], ['hiring_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hiringTeamId', 'memberId', name='uq_hiring_team_member')
    )
    op.create_index(op.f('ix_hiring_team_member_hiringTeamId'), 'hiring_team_member', ['hiringTeamId'], unique=False)
    op.create_index(op.f('ix_hiring_team_member_memberId'), 'hiring_team_member', ['memberId'], unique=False)
    op.create_table('offer_letter',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'WITHDRAWN', name='offerstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('joiningDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respondedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidateToken', sa.String(), nullable=True),
    sa.Column('pdfUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidateToken')
    )
    op.create_index(op.f('ix_offer_letter_applicationId'), 'offer_letter', ['applicationId'], unique=True)
    op.create_index(op.f('ix_offer_letter_createdByMemberId'), 'offer_letter', ['createdByMemberId'], unique=False)
    op.create_index(op.f('ix_offer_letter_organizationId'), 'offer_letter', ['organizationId'], unique=False)
    op.create_index(op.f('ix_offer_letter_status'), 'offer_letter', ['status'], unique=False)
    op.create_table('stage_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('completedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interviewType', sa.Enum('SCREENING', 'TECHNICAL', 'CULTURAL', 'MANAGERIAL', 'HR', 'FINAL', 'OTHER', name='interviewtype'), nullable=True),
    sa.Column('assignmentMode', sa.String(length=32), nullable=True),
    sa.Column('teamId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ONGOING', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='eventstatus'), nullable=False),
    sa.Column('scheduledStartAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduledEndAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meetingUrl', sa.String(), nullable=True),
    sa.Column('googleCalendarEventId', sa.String(length=255), nullable=True),
    sa.Column('googleCalendarEventUrl', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emailSentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['hiring_team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_event_applicationId'), 'stage_event', ['applicationId'], unique=False)
    op.create_index(op.f('ix_stage_event_completedByMemberId'), 'stage_event', ['completedByMemberId'], unique=False)
    op.create_index(op.f('ix_stage_event_createdByMemberId'), 'stage_event', ['createdByMemberId'], unique=False)
    op.create_index(op.f('ix_stage_event_organizationId'), 'stage_event', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_event_stageId'), 'stage_event', ['stageId'], unique=False)
    op.create_index(op.f('ix_stage_event_status'), 'stage_event', ['status'], unique=False)
    op.create_index(op.f('ix_stage_event_teamId'), 'stage_event', ['teamId'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'STRONG_YES', 'YES', 'NEUTRAL', 'NO', 'STRONG_NO', name='interviewoutcome'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_interview_feedback_event_member')
    )
    op.create_index(op.f('ix_interview_feedback_eventId'), 'interview_feedback', ['eventId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_memberId'), 'interview_feedback', ['memberId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_organizationId'), 'interview_feedback', ['organizationId'], unique=False)
    op.create_table('interview_rejection_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('rejectedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_interview_rejection_event_member')
    )
    op.create_index(op.f('ix_interview_rejection_record_eventId'), 'interview_rejection_record', ['eventId'], unique=False)
    op.create_index(op.f('ix_interview_rejection_record_memberId'), 'interview_rejection_record', ['memberId'], unique=False)
    op.create_index(op.f('ix_interview_rejection_record_organizationId'), 'interview_rejection_record', ['organizationId'], unique=False)
    op.create_table('stage_event_participant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('isBackup', sa.Boolean(), nullable=False),
    sa.Column('approvalStatus', sa.String(length=32), nullable=False),
    sa.Column('approvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejectedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduledTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_stage_event_participant')
    )
    op.create_index(op.f('ix_stage_event_participant_eventId'), 'stage_event_participant', ['eventId'], unique=False)
    op.create_index(op.f('ix_stage_event_participant_memberId'), 'stage_event_participant', ['memberId'], unique=False)
    op.create_table('interview_feedback_value',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('feedbackId', sa.String(length=36), nullable=False),
    sa.Column('categoryId', sa.String(length=36), nullable=False),
    sa.Column('numericValue', sa.Float(), nullable=True),
    sa.Column('textValue', sa.Text(), nullable=True),
    sa.Column('booleanValue', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['stage_evaluation_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedbackId'], ['interview_feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feedbackId', 'categoryId', name='uq_interview_feedback_value_category')
    )
    op.create_index(op.f('ix_interview_feedback_value_categoryId'), 'interview_feedback_value', ['categoryId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_value_feedbackId'), 'interview_feedback_value', ['feedbackId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_feedback_value_feedbackId'), table_name='interview_feedback_value')
    op.drop_index(op.f('ix_interview_feedback_value_categoryId'), table_name='interview_feedback_value')
    op.drop_table('interview_feedback_value')
    op.drop_index(op.f('ix_stage_event_participant_memberId'), table_name='stage_event_participant')
    op.drop_index(op.f('ix_stage_event_participant_eventId'), table_name='stage_event_participant')
    op.drop_table('stage_event_participant')
    op.drop_index(op.f('ix_interview_rejection_record_organizationId'), table_name='interview_rejection_record')
    op.drop_index(op.f('ix_interview_rejection_record_memberId'), table_name='interview_rejection_record')
    op.drop_index(op.f('ix_interview_rejection_record_eventId'), table_name='interview_rejection_record')
    op.drop_table('interview_rejection_record')
    op.drop_index(op.f('ix_interview_feedback_organizationId'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_memberId'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_eventId'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index(op.f('ix_stage_event_teamId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_status'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_stageId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_organizationId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_createdByMemberId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_completedByMemberId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_applicationId'), table_name='stage_event')
    op.drop_table('stage_event')
    op.drop_index(op.f('ix_offer_letter_status'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_organizationId'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_createdByMemberId'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_applicationId'), table_name='offer_letter')
    op.drop_table('offer_letter')
    op.drop_index(op.f('ix_hiring_team_member_memberId'), table_name='hiring_team_member')
    op.drop_index(op.f('ix_hiring_team_member_hiringTeamId'), table_name='hiring_team_member')
    op.drop_table('hiring_team_member')
    op.drop_index(op.f('ix_candidate_resume_analysis_status'), table_name='candidate_resume_analysis')
    op.drop_index(op.f('ix_candidate_resume_analysis_organizationId'), table_name='candidate_resume_analysis')
    op.drop_index('ix_candidate_resume_analysis_org_status', table_name='candidate_resume_analysis')
    op.drop_index('ix_candidate_resume_analysis_org_application', table_name='candidate_resume_analysis')
    op.drop_index(op.f('ix_candidate_resume_analysis_applicationId'), table_name='candidate_resume_analysis')
    op.drop_table('candidate_resume_analysis')
    op.drop_index('ix_candidate_note_org_author', table_name='candidate_application_note')
    op.drop_index('ix_candidate_note_org_application', table_name='candidate_application_note')
    op.drop_index(op.f('ix_candidate_application_note_organizationId'), table_name='candidate_application_note')
    op.drop_index(op.f('ix_candidate_application_note_authorMemberId'), table_name='candidate_application_note')
    op.drop_index(op.f('ix_candidate_application_note_applicationId'), table_name='candidate_application_note')
    op.drop_table('candidate_application_note')
    op.drop_index(op.f('ix_application_stage_history_toStageId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_organizationId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_movedByMemberId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_fromStageId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_applicationId'), table_name='application_stage_history')
    op.drop_table('application_stage_history')
    op.drop_index(op.f('ix_stage_evaluation_workspace_stageId'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('ix_stage_evaluation_workspace_organizationId'), table_name='stage_evaluation_workspace')
    op.drop_index('ix_stage_evaluation_workspace_org_stage', table_name='stage_evaluation_workspace')
    op.drop_index(op.f('ix_stage_evaluation_workspace_createdByMemberId'), table_name='stage_evaluation_workspace')
    op.drop_table('stage_evaluation_workspace')
    op.drop_index(op.f('ix_stage_evaluation_category_stageId'), table_name='stage_evaluation_category')
    op.drop_index(op.f('ix_stage_evaluation_category_organizationId'), table_name='stage_evaluation_category')
    op.drop_index('ix_stage_evaluation_category_org_stage', table_name='stage_evaluation_category')
    op.drop_table('stage_evaluation_category')
    op.drop_index(op.f('ix_hiring_team_stageId'), table_name='hiring_team')
    op.drop_index(op.f('ix_hiring_team_organizationId'), table_name='hiring_team')
    op.drop_index(op.f('ix_hiring_team_jobPostingId'), table_name='hiring_team')
    op.drop_index('hiring_team_organizationId_isActive_idx', table_name='hiring_team')
    op.drop_index('hiring_team_organizationId_idx', table_name='hiring_team')
    op.drop_index('hiring_team_jobPostingId_idx', table_name='hiring_team')
    op.drop_table('hiring_team')
    op.drop_index(op.f('ix_candidate_application_pipelineStageId'), table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_organizationId'), table_name='candidate_application')
    op.drop_index('ix_candidate_application_org_stage', table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_jobPostingId'), table_name='candidate_application')
    op.drop_table('candidate_application')
    op.drop_index('project_task_projectId_idx', table_name='project_task')
    op.drop_table('project_task')
    op.drop_index('project_member_projectId_idx', table_name='project_member')
    op.drop_index('project_member_memberId_idx', table_name='project_member')
    op.drop_table('project_member')
    op.drop_index(op.f('ix_pipeline_stage_stageId'), table_name='pipeline_stage')
    op.drop_index(op.f('ix_pipeline_stage_organizationId'), table_name='pipeline_stage')
    op.drop_index(op.f('ix_pipeline_stage_jobPostingId'), table_name='pipeline_stage')
    op.drop_table('pipeline_stage')
    op.drop_index(op.f('ix_job_requisition_rules_requisitionId'), table_name='job_requisition_rules')
    op.drop_index(op.f('ix_job_requisition_rules_organizationId'), table_name='job_requisition_rules')
    op.drop_index('ix_job_requisition_rules_org_requisition', table_name='job_requisition_rules')
    op.drop_index('ix_job_requisition_rules_org_posting', table_name='job_requisition_rules')
    op.drop_index(op.f('ix_job_requisition_rules_jobPostingId'), table_name='job_requisition_rules')
    op.drop_table('job_requisition_rules')
    op.drop_index('team_member_teamId_idx', table_name='team_member')
    op.drop_index('team_member_memberId_idx', table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_requisition_approval_requisitionId'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_organizationId'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_decision'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_approverId'), table_name='requisition_approval')
    op.drop_table('requisition_approval')
    op.drop_index(op.f('ix_requisition_activity_log_requisitionId'), table_name='requisition_activity_log')
    op.drop_index(op.f('ix_requisition_activity_log_organizationId'), table_name='requisition_activity_log')
    op.drop_index('ix_requisition_activity_log_org_action', table_name='requisition_activity_log')
    op.drop_index(op.f('ix_requisition_activity_log_createdAt'), table_name='requisition_activity_log')
    op.drop_index(op.f('ix_requisition_activity_log_actorId'), table_name='requisition_activity_log')
    op.drop_index(op.f('ix_requisition_activity_log_action'), table_name='requisition_activity_log')
    op.drop_table('requisition_activity_log')
    op.drop_index('project_teamId_idx', table_name='project')
    op.drop_index('project_organizationId_status_idx', table_name='project')
    op.drop_index('project_organizationId_idx', table_name='project')
    op.drop_index('project_organizationId_deletedAt_idx', table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_job_posting_status'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_requisitionId'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_organizationId'), table_name='job_posting')
    op.drop_table('job_posting')
    op.drop_index('team_organizationId_status_idx', table_name='team')
    op.drop_index('team_organizationId_idx', table_name='team')
    op.drop_index('team_leadMemberId_idx', table_name='team')
    op.drop_index('team_departmentId_idx', table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_job_requisition_status'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_replacementForId'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_raisedById'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_organizationId'), table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_status', table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_replacement', table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_raised_by', table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_departmentId'), table_name='job_requisition')
    op.drop_table('job_requisition')
    op.drop_index('departmentMember_memberId_idx', table_name='departmentMember')
    op.drop_index('departmentMember_departmentId_idx', table_name='departmentMember')
    op.drop_table('departmentMember')
    op.drop_index('asset_maintenance_log_ticketMode_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_ticketId_key', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_status_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_serviceDate_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_organizationId_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_category_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_assetId_idx', table_name='asset_maintenance_log')
    op.drop_table('asset_maintenance_log')
    op.drop_index('asset_assignment_returnDate_idx', table_name='asset_assignment')
    op.drop_index('asset_assignment_memberId_idx', table_name='asset_assignment')
    op.drop_index('asset_assignment_assetId_idx', table_name='asset_assignment')
    op.drop_table('asset_assignment')
    op.drop_index('leave_request_organizationId_status_idx', table_name='leave_request')
    op.drop_index('leave_request_organizationId_startDate_idx', table_name='leave_request')
    op.drop_index('leave_request_organizationId_startDate_endDate_idx', table_name='leave_request')
    op.drop_index('leave_request_organizationId_memberId_idx', table_name='leave_request')
    op.drop_index('leave_request_organizationId_leaveTypeId_idx', table_name='leave_request')
    op.drop_index('leave_request_organizationId_idx', table_name='leave_request')
    op.drop_index('leave_request_approvedById_idx', table_name='leave_request')
    op.drop_table('leave_request')
    op.drop_index('leave_balance_organizationId_memberId_year_idx', table_name='leave_balance')
    op.drop_index('leave_balance_organizationId_leaveTypeId_year_idx', table_name='leave_balance')
    op.drop_index('leave_balance_organizationId_idx', table_name='leave_balance')
    op.drop_table('leave_balance')
    op.drop_index('department_parentDepartmentId_idx', table_name='department')
    op.drop_index('department_organizationId_status_idx', table_name='department')
    op.drop_index('department_organizationId_idx', table_name='department')
    op.drop_index('department_headMemberId_idx', table_name='department')
    op.drop_table('department')
    op.drop_index('asset_unit_status_idx', table_name='asset_unit')
    op.drop_index('asset_unit_holder_idx', table_name='asset_unit')
    op.drop_index('asset_unit_asset_idx', table_name='asset_unit')
    op.drop_table('asset_unit')
    op.drop_index('asset_custom_field_def_idx', table_name='asset_custom_field_value')
    op.drop_index('asset_custom_field_asset_idx', table_name='asset_custom_field_value')
    op.drop_index('asset_custom_field_asset_def_idx', table_name='asset_custom_field_value')
    op.drop_table('asset_custom_field_value')
    op.drop_index(op.f('ix_candidate_organizationId'), table_name='candidate')
    op.drop_table('candidate')
    op.drop_index('attendanceWorkLog_projectTaskId_idx', table_name='attendanceWorkLog')
    op.drop_index('attendanceWorkLog_projectId_idx', table_name='attendanceWorkLog')
    op.drop_index('attendanceWorkLog_organizationId_idx', table_name='attendanceWorkLog')
    op.drop_index('attendanceWorkLog_organizationId_employeeId_idx', table_name='attendanceWorkLog')
    op.drop_index('attendanceWorkLog_organizationId_date_idx', table_name='attendanceWorkLog')
    op.drop_index('attendanceWorkLog_attendanceRecordId_idx', table_name='attendanceWorkLog')
    op.drop_table('attendanceWorkLog')
    op.drop_index(op.f('ix_asset_id_definitions_organizationId'), table_name='asset_id_definitions')
    op.drop_table('asset_id_definitions')
    op.drop_index('asset_cat_field_def_cat_idx', table_name='asset_category_field_definition')
    op.drop_table('asset_category_field_definition')
    op.drop_table('workHourPolicy')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_organization_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index('public_holiday_master_year_location_idx', table_name='public_holiday_master')
    op.drop_table('public_holiday_master')
    op.drop_index(op.f('ix_monthly_plans_user_id'), table_name='monthly_plans')
    op.drop_index(op.f('ix_monthly_plans_organization_id'), table_name='monthly_plans')
    op.drop_table('monthly_plans')
    op.drop_index('leave_type_organizationId_idx', table_name='leave_type')
    op.drop_index('leave_type_organizationId_deletedAt_idx', table_name='leave_type')
    op.drop_table('leave_type')
    op.drop_index('holiday_organizationId_idx', table_name='holiday')
    op.drop_index('holiday_organizationId_holidayDate_idx', table_name='holiday')
    op.drop_index('holiday_organizationId_deletedAt_idx', table_name='holiday')
    op.drop_table('holiday')
    op.drop_index('attendanceRecord_projectTaskId_idx', table_name='attendanceRecord')
    op.drop_index('attendanceRecord_projectId_idx', table_name='attendanceRecord')
    op.drop_index('attendanceRecord_organizationId_idx', table_name='attendanceRecord')
    op.drop_index('attendanceRecord_organizationId_employeeId_idx', table_name='attendanceRecord')
    op.drop_index('attendanceRecord_organizationId_date_idx', table_name='attendanceRecord')
    op.drop_table('attendanceRecord')
    op.drop_index('asset_category_def_org_name_idx', table_name='asset_category_definition')
    op.drop_index('asset_category_def_org_idx', table_name='asset_category_definition')
    op.drop_table('asset_category_definition')
    op.drop_index('asset_organizationId_status_idx', table_name='asset')
    op.drop_index('asset_organizationId_idx', table_name='asset')
    op.drop_index('asset_organizationId_deletedAt_idx', table_name='asset')
    op.drop_index('asset_organizationId_category_idx', table_name='asset')
    op.drop_index('asset_organizationId_assetCode_idx', table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
