"""db reset init

Revision ID: 39d16f2699f3
Revises: 
Create Date: 2026-05-18 13:02:18.341760
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39d16f2699f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('assetCode', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('categoryDefinitionId', sa.String(length=36), nullable=True),
    sa.Column('serialNumber', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('purchaseDate', sa.Date(), nullable=True),
    sa.Column('purchasePrice', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('warrantyExpiryDate', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=40), server_default='GOOD', nullable=False),
    sa.Column('status', sa.String(length=40), server_default='AVAILABLE', nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_organizationId_assetCode_idx', 'asset', ['organizationId', 'assetCode'], unique=False)
    op.create_index('asset_organizationId_category_idx', 'asset', ['organizationId', 'category'], unique=False)
    op.create_index('asset_organizationId_deletedAt_idx', 'asset', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('asset_organizationId_idx', 'asset', ['organizationId'], unique=False)
    op.create_index('asset_organizationId_status_idx', 'asset', ['organizationId', 'status'], unique=False)
    op.create_table('asset_category_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('asset_code', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_category_def_org_idx', 'asset_category_definition', ['organizationId'], unique=False)
    op.create_index('asset_category_def_org_name_idx', 'asset_category_definition', ['organizationId', 'name'], unique=False)
    op.create_table('monthly_plans',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_location', sa.String(length=40), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'date', name='uq_monthly_plan_org_user_date')
    )
    op.create_index(op.f('ix_monthly_plans_organization_id'), 'monthly_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_monthly_plans_user_id'), 'monthly_plans', ['user_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_location', sa.String(length=40), nullable=False),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'date', name='uq_weekly_plan_org_user_date')
    )
    op.create_index(op.f('ix_weekly_plans_organization_id'), 'weekly_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_table('asset_category_field_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('categoryId', sa.String(length=36), nullable=False),
    sa.Column('fieldName', sa.String(length=100), nullable=False),
    sa.Column('fieldType', sa.String(length=20), nullable=False),
    sa.Column('fieldOptions', sa.JSON(), nullable=True),
    sa.Column('isRequired', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('displayOrder', sa.Integer(), server_default='0', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['asset_category_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_cat_field_def_cat_idx', 'asset_category_field_definition', ['categoryId'], unique=False)
    op.create_table('asset_id_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('assetIdName', sa.String(length=120), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id_definitions_organizationId'), 'asset_id_definitions', ['organizationId'], unique=False)
    op.create_table('asset_custom_field_value',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('fieldDefinitionId', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fieldDefinitionId'], ['asset_category_field_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_custom_field_asset_def_idx', 'asset_custom_field_value', ['assetId', 'fieldDefinitionId'], unique=True)
    op.create_index('asset_custom_field_asset_idx', 'asset_custom_field_value', ['assetId'], unique=False)
    op.create_index('asset_custom_field_def_idx', 'asset_custom_field_value', ['fieldDefinitionId'], unique=False)
    op.create_table('asset_unit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('serialNumber', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='AVAILABLE', nullable=False),
    sa.Column('currentHolderMemberId', sa.String(length=36), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currentHolderMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_unit_asset_idx', 'asset_unit', ['assetId'], unique=False)
    op.create_index('asset_unit_holder_idx', 'asset_unit', ['currentHolderMemberId'], unique=False)
    op.create_index('asset_unit_status_idx', 'asset_unit', ['status'], unique=False)
    op.create_table('hiring_team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('hiring_team_jobPostingId_idx', 'hiring_team', ['jobPostingId'], unique=False)
    op.create_index('hiring_team_organizationId_idx', 'hiring_team', ['organizationId'], unique=False)
    op.create_index('hiring_team_organizationId_isActive_idx', 'hiring_team', ['organizationId', 'isActive'], unique=False)
    op.create_index(op.f('ix_hiring_team_jobPostingId'), 'hiring_team', ['jobPostingId'], unique=False)
    op.create_index(op.f('ix_hiring_team_organizationId'), 'hiring_team', ['organizationId'], unique=False)
    op.create_index(op.f('ix_hiring_team_stageId'), 'hiring_team', ['stageId'], unique=False)
    op.create_table('asset_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('assetUnitId', sa.String(length=36), nullable=True),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('providedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('providedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('conditionWhileProviding', sa.String(length=40), nullable=False),
    sa.Column('provideNotes', sa.Text(), nullable=True),
    sa.Column('returnDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returnedCondition', sa.String(length=40), nullable=True),
    sa.Column('receivedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('returnNotes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assetUnitId'], ['asset_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['providedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receivedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_assignment_assetId_idx', 'asset_assignment', ['assetId'], unique=False)
    op.create_index('asset_assignment_memberId_idx', 'asset_assignment', ['memberId'], unique=False)
    op.create_index('asset_assignment_returnDate_idx', 'asset_assignment', ['returnDate'], unique=False)
    op.create_table('asset_maintenance_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=False),
    sa.Column('assetUnitId', sa.String(length=36), nullable=True),
    sa.Column('loggedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('maintenanceType', sa.String(length=40), nullable=False),
    sa.Column('issueDescription', sa.Text(), nullable=False),
    sa.Column('serviceDate', sa.Date(), nullable=False),
    sa.Column('expectedCompletionDate', sa.Date(), nullable=True),
    sa.Column('completedDate', sa.Date(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='OPEN', nullable=False),
    sa.Column('conditionBeforeMaintenance', sa.String(length=40), nullable=True),
    sa.Column('conditionAfterMaintenance', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assetUnitId'], ['asset_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['loggedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('asset_maintenance_log_assetId_idx', 'asset_maintenance_log', ['assetId'], unique=False)
    op.create_index('asset_maintenance_log_serviceDate_idx', 'asset_maintenance_log', ['serviceDate'], unique=False)
    op.create_index('asset_maintenance_log_status_idx', 'asset_maintenance_log', ['status'], unique=False)
    op.create_table('hiring_team_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hiringTeamId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hiringTeamId'], ['hiring_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hiringTeamId', 'memberId', name='uq_hiring_team_member')
    )
    op.create_index(op.f('ix_hiring_team_member_hiringTeamId'), 'hiring_team_member', ['hiringTeamId'], unique=False)
    op.create_index(op.f('ix_hiring_team_member_memberId'), 'hiring_team_member', ['memberId'], unique=False)
    op.create_table('job_requisition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=True),
    sa.Column('employmentType', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employmenttype'), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('salaryMin', sa.Float(), nullable=True),
    sa.Column('salaryMax', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('isRemote', sa.Boolean(), nullable=False),
    sa.Column('raisedById', sa.String(length=36), nullable=False),
    sa.Column('targetDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CLOSED', name='jobrequisitionstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raisedById'], ['member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requisition_departmentId'), 'job_requisition', ['departmentId'], unique=False)
    op.create_index('ix_job_requisition_org_raised_by', 'job_requisition', ['organizationId', 'raisedById'], unique=False)
    op.create_index('ix_job_requisition_org_status', 'job_requisition', ['organizationId', 'status'], unique=False)
    op.create_index(op.f('ix_job_requisition_organizationId'), 'job_requisition', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_requisition_raisedById'), 'job_requisition', ['raisedById'], unique=False)
    op.create_index(op.f('ix_job_requisition_status'), 'job_requisition', ['status'], unique=False)
    op.create_table('offer_letter',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'WITHDRAWN', name='offerstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('joiningDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respondedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('candidateToken', sa.String(), nullable=True),
    sa.Column('pdfUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidateToken')
    )
    op.create_index(op.f('ix_offer_letter_applicationId'), 'offer_letter', ['applicationId'], unique=True)
    op.create_index(op.f('ix_offer_letter_createdByMemberId'), 'offer_letter', ['createdByMemberId'], unique=False)
    op.create_index(op.f('ix_offer_letter_organizationId'), 'offer_letter', ['organizationId'], unique=False)
    op.create_index(op.f('ix_offer_letter_status'), 'offer_letter', ['status'], unique=False)
    op.create_table('stage_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('stageId', sa.String(length=36), nullable=False),
    sa.Column('createdByMemberId', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interviewType', sa.Enum('SCREENING', 'TECHNICAL', 'CULTURAL', 'MANAGERIAL', 'HR', 'FINAL', 'OTHER', name='interviewtype'), nullable=True),
    sa.Column('assignmentMode', sa.String(length=32), nullable=True),
    sa.Column('teamId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', name='eventstatus'), nullable=False),
    sa.Column('scheduledStartAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduledEndAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meetingUrl', sa.String(), nullable=True),
    sa.Column('googleCalendarEventId', sa.String(length=255), nullable=True),
    sa.Column('googleCalendarEventUrl', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emailSentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['createdByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stageId'], ['pipeline_stage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['hiring_team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_event_applicationId'), 'stage_event', ['applicationId'], unique=False)
    op.create_index(op.f('ix_stage_event_createdByMemberId'), 'stage_event', ['createdByMemberId'], unique=False)
    op.create_index(op.f('ix_stage_event_organizationId'), 'stage_event', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_event_stageId'), 'stage_event', ['stageId'], unique=False)
    op.create_index(op.f('ix_stage_event_status'), 'stage_event', ['status'], unique=False)
    op.create_index(op.f('ix_stage_event_teamId'), 'stage_event', ['teamId'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leadMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leadMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'departmentId', 'name', name='team_organizationId_departmentId_name_key')
    )
    op.create_index('team_departmentId_idx', 'team', ['departmentId'], unique=False)
    op.create_index('team_leadMemberId_idx', 'team', ['leadMemberId'], unique=False)
    op.create_index('team_organizationId_idx', 'team', ['organizationId'], unique=False)
    op.create_index('team_organizationId_status_idx', 'team', ['organizationId', 'status'], unique=False)
    op.create_table('interview_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('PENDING', 'STRONG_YES', 'YES', 'NEUTRAL', 'NO', 'STRONG_NO', name='interviewoutcome'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_interview_feedback_event_member')
    )
    op.create_index(op.f('ix_interview_feedback_eventId'), 'interview_feedback', ['eventId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_memberId'), 'interview_feedback', ['memberId'], unique=False)
    op.create_index(op.f('ix_interview_feedback_organizationId'), 'interview_feedback', ['organizationId'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clientName', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budgetedHours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_organizationId_deletedAt_idx', 'project', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('project_organizationId_idx', 'project', ['organizationId'], unique=False)
    op.create_index('project_organizationId_status_idx', 'project', ['organizationId', 'status'], unique=False)
    op.create_index('project_teamId_idx', 'project', ['teamId'], unique=False)
    op.create_table('requisition_approval',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=False),
    sa.Column('approverId', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requisitionapprovaldecision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decidedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approverId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisitionId', 'approverId', name='uq_requisition_approval_requisition_approver')
    )
    op.create_index(op.f('ix_requisition_approval_approverId'), 'requisition_approval', ['approverId'], unique=False)
    op.create_index(op.f('ix_requisition_approval_decision'), 'requisition_approval', ['decision'], unique=False)
    op.create_index(op.f('ix_requisition_approval_organizationId'), 'requisition_approval', ['organizationId'], unique=False)
    op.create_index(op.f('ix_requisition_approval_requisitionId'), 'requisition_approval', ['requisitionId'], unique=False)
    op.create_table('stage_event_participant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('eventId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('isBackup', sa.Boolean(), nullable=False),
    sa.Column('approvalStatus', sa.String(length=32), nullable=False),
    sa.Column('approvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejectedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduledTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId', 'memberId', name='uq_stage_event_participant')
    )
    op.create_index(op.f('ix_stage_event_participant_eventId'), 'stage_event_participant', ['eventId'], unique=False)
    op.create_index(op.f('ix_stage_event_participant_memberId'), 'stage_event_participant', ['memberId'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('joinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'memberId', name='team_member_teamId_memberId_key')
    )
    op.create_index('team_member_memberId_idx', 'team_member', ['memberId'], unique=False)
    op.create_index('team_member_teamId_idx', 'team_member', ['teamId'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('allocatedHours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId', 'memberId', name='project_member_projectId_memberId_key')
    )
    op.create_index('project_member_memberId_idx', 'project_member', ['memberId'], unique=False)
    op.create_index('project_member_projectId_idx', 'project_member', ['projectId'], unique=False)
    op.create_table('project_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_task_projectId_idx', 'project_task', ['projectId'], unique=False)
    op.drop_index(op.f('application_stage_history_applicationId_idx'), table_name='application_stage_history')
    op.drop_index(op.f('application_stage_history_fromStageId_idx'), table_name='application_stage_history')
    op.drop_index(op.f('application_stage_history_movedByMemberId_idx'), table_name='application_stage_history')
    op.drop_index(op.f('application_stage_history_organizationId_idx'), table_name='application_stage_history')
    op.drop_index(op.f('application_stage_history_toStageId_idx'), table_name='application_stage_history')
    op.create_index(op.f('ix_application_stage_history_applicationId'), 'application_stage_history', ['applicationId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_fromStageId'), 'application_stage_history', ['fromStageId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_movedByMemberId'), 'application_stage_history', ['movedByMemberId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_organizationId'), 'application_stage_history', ['organizationId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_toStageId'), 'application_stage_history', ['toStageId'], unique=False)
    op.drop_constraint(op.f('application_stage_history_organizationId_fkey'), 'application_stage_history', type_='foreignkey')
    op.drop_constraint(op.f('application_stage_history_fromStageId_fkey'), 'application_stage_history', type_='foreignkey')
    op.drop_constraint(op.f('application_stage_history_applicationId_fkey'), 'application_stage_history', type_='foreignkey')
    op.drop_constraint(op.f('application_stage_history_movedByMemberId_fkey'), 'application_stage_history', type_='foreignkey')
    op.drop_constraint(op.f('application_stage_history_toStageId_fkey'), 'application_stage_history', type_='foreignkey')
    op.create_foreign_key(None, 'application_stage_history', 'member', ['movedByMemberId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'application_stage_history', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application_stage_history', 'pipeline_stage', ['fromStageId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'application_stage_history', 'candidate_application', ['applicationId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application_stage_history', 'pipeline_stage', ['toStageId'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('attendanceRecord_employeeId_date_key'), table_name='attendanceRecord')
    op.create_unique_constraint('attendanceRecord_employeeId_date_key', 'attendanceRecord', ['employeeId', 'date'])
    op.drop_constraint(op.f('attendanceWorkLog_attendanceRecordId_fkey'), 'attendanceWorkLog', type_='foreignkey')
    op.create_foreign_key(None, 'attendanceWorkLog', 'attendanceRecord', ['attendanceRecordId'], ['id'], ondelete='CASCADE')
    op.add_column('candidate', sa.Column('portfolioUrl', sa.String(), nullable=True))
    op.add_column('candidate', sa.Column('currentCompany', sa.String(), nullable=True))
    op.add_column('candidate', sa.Column('currentTitle', sa.String(), nullable=True))
    op.add_column('candidate', sa.Column('totalExperience', sa.String(), nullable=True))
    op.drop_index(op.f('candidate_organizationId_email_key'), table_name='candidate')
    op.drop_index(op.f('candidate_organizationId_idx'), table_name='candidate')
    op.drop_index(op.f('candidate_userId_idx'), table_name='candidate')
    op.create_index(op.f('ix_candidate_organizationId'), 'candidate', ['organizationId'], unique=False)
    op.create_index(op.f('ix_candidate_userId'), 'candidate', ['userId'], unique=False)
    op.create_unique_constraint('uq_candidate_org_email', 'candidate', ['organizationId', 'email'])
    op.drop_constraint(op.f('candidate_organizationId_fkey'), 'candidate', type_='foreignkey')
    op.drop_constraint(op.f('candidate_userId_fkey'), 'candidate', type_='foreignkey')
    op.create_foreign_key(None, 'candidate', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidate', 'user', ['userId'], ['id'], ondelete='SET NULL')
    op.add_column('candidate_application', sa.Column('internalNotes', sa.Text(), nullable=True))
    op.add_column('candidate_application', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_index(op.f('candidate_application_candidateId_jobPostingId_key'), table_name='candidate_application')
    op.drop_index(op.f('candidate_application_jobPostingId_idx'), table_name='candidate_application')
    op.drop_index(op.f('candidate_application_organizationId_idx'), table_name='candidate_application')
    op.drop_index(op.f('candidate_application_organizationId_pipelineStageId_idx'), table_name='candidate_application')
    op.drop_index(op.f('candidate_application_pipelineStageId_idx'), table_name='candidate_application')
    op.create_index(op.f('ix_candidate_application_jobPostingId'), 'candidate_application', ['jobPostingId'], unique=False)
    op.create_index('ix_candidate_application_org_stage', 'candidate_application', ['organizationId', 'pipelineStageId'], unique=False)
    op.create_index(op.f('ix_candidate_application_organizationId'), 'candidate_application', ['organizationId'], unique=False)
    op.create_index(op.f('ix_candidate_application_pipelineStageId'), 'candidate_application', ['pipelineStageId'], unique=False)
    op.create_unique_constraint('uq_candidate_job_application', 'candidate_application', ['candidateId', 'jobPostingId'])
    op.drop_constraint(op.f('candidate_application_pipelineStageId_fkey'), 'candidate_application', type_='foreignkey')
    op.drop_constraint(op.f('candidate_application_candidateId_fkey'), 'candidate_application', type_='foreignkey')
    op.drop_constraint(op.f('candidate_application_organizationId_fkey'), 'candidate_application', type_='foreignkey')
    op.drop_constraint(op.f('candidate_application_jobPostingId_fkey'), 'candidate_application', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_application', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidate_application', 'candidate', ['candidateId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidate_application', 'pipeline_stage', ['pipelineStageId'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'candidate_application', 'job_posting', ['jobPostingId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('department_parentDepartmentId_fkey'), 'department', type_='foreignkey')
    op.create_foreign_key(None, 'department', 'department', ['parentDepartmentId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'department', 'member', ['headMemberId'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('departmentMember_departmentId_memberId_key'), table_name='departmentMember')
    op.create_unique_constraint('departmentMember_departmentId_memberId_key', 'departmentMember', ['departmentId', 'memberId'])
    op.drop_constraint(op.f('departmentMember_memberId_fkey'), 'departmentMember', type_='foreignkey')
    op.drop_constraint(op.f('departmentMember_departmentId_fkey'), 'departmentMember', type_='foreignkey')
    op.create_foreign_key(None, 'departmentMember', 'member', ['memberId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'departmentMember', 'department', ['departmentId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('holiday_organizationId_fkey'), 'holiday', type_='foreignkey')
    op.add_column('job_posting', sa.Column('slug', sa.String(length=160), nullable=False))
    op.drop_index(op.f('job_posting_organizationId_idx'), table_name='job_posting')
    op.drop_index(op.f('job_posting_organizationId_status_idx'), table_name='job_posting')
    op.create_index(op.f('ix_job_posting_organizationId'), 'job_posting', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_posting_status'), 'job_posting', ['status'], unique=False)
    op.create_unique_constraint('uq_job_posting_org_slug', 'job_posting', ['organizationId', 'slug'])
    op.drop_constraint(op.f('job_posting_organizationId_fkey'), 'job_posting', type_='foreignkey')
    op.create_foreign_key(None, 'job_posting', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('leave_balance_organizationId_memberId_leaveTypeId_year_key'), table_name='leave_balance')
    op.create_unique_constraint('leave_balance_org_member_type_year_key', 'leave_balance', ['organizationId', 'memberId', 'leaveTypeId', 'year'])
    op.drop_constraint(op.f('leave_balance_leaveTypeId_fkey'), 'leave_balance', type_='foreignkey')
    op.drop_constraint(op.f('leave_balance_memberId_fkey'), 'leave_balance', type_='foreignkey')
    op.drop_constraint(op.f('leave_balance_organizationId_fkey'), 'leave_balance', type_='foreignkey')
    op.create_foreign_key(None, 'leave_balance', 'leave_type', ['leaveTypeId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'leave_balance', 'member', ['memberId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('leave_request_approvedById_fkey'), 'leave_request', type_='foreignkey')
    op.drop_constraint(op.f('leave_request_leaveTypeId_fkey'), 'leave_request', type_='foreignkey')
    op.drop_constraint(op.f('leave_request_memberId_fkey'), 'leave_request', type_='foreignkey')
    op.drop_constraint(op.f('leave_request_organizationId_fkey'), 'leave_request', type_='foreignkey')
    op.create_foreign_key(None, 'leave_request', 'member', ['memberId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'leave_request', 'member', ['approvedById'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'leave_request', 'leave_type', ['leaveTypeId'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('leave_type_organizationId_name_key'), table_name='leave_type')
    op.create_unique_constraint('leave_type_organizationId_name_key', 'leave_type', ['organizationId', 'name'])
    op.drop_constraint(op.f('leave_type_organizationId_fkey'), 'leave_type', type_='foreignkey')
    op.add_column('pipeline_stage', sa.Column('stageId', sa.String(length=36), nullable=True))
    op.add_column('pipeline_stage', sa.Column('slug', sa.String(length=160), nullable=False))
    op.drop_index(op.f('pipeline_stage_jobPostingId_idx'), table_name='pipeline_stage')
    op.drop_index(op.f('pipeline_stage_jobPostingId_order_key'), table_name='pipeline_stage')
    op.drop_index(op.f('pipeline_stage_organizationId_idx'), table_name='pipeline_stage')
    op.create_index(op.f('ix_pipeline_stage_jobPostingId'), 'pipeline_stage', ['jobPostingId'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_organizationId'), 'pipeline_stage', ['organizationId'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_stageId'), 'pipeline_stage', ['stageId'], unique=False)
    op.create_unique_constraint('uq_pipeline_stage_job_slug', 'pipeline_stage', ['jobPostingId', 'slug'])
    op.create_unique_constraint('uq_pipeline_stage_order', 'pipeline_stage', ['jobPostingId', 'order'])
    op.drop_constraint(op.f('pipeline_stage_jobPostingId_fkey'), 'pipeline_stage', type_='foreignkey')
    op.drop_constraint(op.f('pipeline_stage_organizationId_fkey'), 'pipeline_stage', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_stage', 'job_posting', ['jobPostingId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_stage', 'pipeline_stage', ['stageId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_stage', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.add_column('public_holiday_master', sa.Column('isHoliday', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('public_holiday_master_date_name_location_key'), table_name='public_holiday_master')
    op.create_unique_constraint('public_holiday_master_date_name_location_key', 'public_holiday_master', ['date', 'name', 'location'])
    # op.drop_index(op.f('role_organizationId_id_key'), table_name='role')
    # op.drop_index(op.f('role_organizationId_name_key'), table_name='role')
    op.drop_index(op.f('stage_evaluation_category_organizationId_idx'), table_name='stage_evaluation_category')
    op.drop_index(op.f('stage_evaluation_category_organizationId_stageId_idx'), table_name='stage_evaluation_category')
    op.drop_index(op.f('stage_evaluation_category_stageId_idx'), table_name='stage_evaluation_category')
    op.drop_index(op.f('stage_evaluation_category_stageId_order_key'), table_name='stage_evaluation_category')
    op.create_index('ix_stage_evaluation_category_org_stage', 'stage_evaluation_category', ['organizationId', 'stageId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_category_organizationId'), 'stage_evaluation_category', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_category_stageId'), 'stage_evaluation_category', ['stageId'], unique=False)
    op.create_unique_constraint('uq_stage_evaluation_category_order', 'stage_evaluation_category', ['stageId', 'order'])
    op.drop_constraint(op.f('stage_evaluation_category_organizationId_fkey'), 'stage_evaluation_category', type_='foreignkey')
    op.drop_constraint(op.f('stage_evaluation_category_stageId_fkey'), 'stage_evaluation_category', type_='foreignkey')
    op.create_foreign_key(None, 'stage_evaluation_category', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stage_evaluation_category', 'pipeline_stage', ['stageId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('stage_evaluation_workspace_createdByMemberId_idx'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('stage_evaluation_workspace_organizationId_idx'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('stage_evaluation_workspace_organizationId_stageId_idx'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('stage_evaluation_workspace_organizationId_stageId_key'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('stage_evaluation_workspace_stageId_idx'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('stage_evaluation_workspace_stageId_key'), table_name='stage_evaluation_workspace')
    op.create_index(op.f('ix_stage_evaluation_workspace_createdByMemberId'), 'stage_evaluation_workspace', ['createdByMemberId'], unique=False)
    op.create_index('ix_stage_evaluation_workspace_org_stage', 'stage_evaluation_workspace', ['organizationId', 'stageId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_workspace_organizationId'), 'stage_evaluation_workspace', ['organizationId'], unique=False)
    op.create_index(op.f('ix_stage_evaluation_workspace_stageId'), 'stage_evaluation_workspace', ['stageId'], unique=False)
    op.create_unique_constraint('uq_stage_evaluation_workspace_org_stage', 'stage_evaluation_workspace', ['organizationId', 'stageId'])
    op.create_unique_constraint('uq_stage_evaluation_workspace_stage', 'stage_evaluation_workspace', ['stageId'])
    op.drop_constraint(op.f('stage_evaluation_workspace_stageId_fkey'), 'stage_evaluation_workspace', type_='foreignkey')
    op.drop_constraint(op.f('stage_evaluation_workspace_organizationId_fkey'), 'stage_evaluation_workspace', type_='foreignkey')
    op.drop_constraint(op.f('stage_evaluation_workspace_createdByMemberId_fkey'), 'stage_evaluation_workspace', type_='foreignkey')
    op.create_foreign_key(None, 'stage_evaluation_workspace', 'pipeline_stage', ['stageId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stage_evaluation_workspace', 'organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stage_evaluation_workspace', 'member', ['createdByMemberId'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('workHourPolicy_organizationId_key'), table_name='workHourPolicy')
    op.create_unique_constraint('workHourPolicy_organizationId_key', 'workHourPolicy', ['organizationId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workHourPolicy_organizationId_key', 'workHourPolicy', type_='unique')
    op.create_index(op.f('workHourPolicy_organizationId_key'), 'workHourPolicy', ['organizationId'], unique=True)
    op.drop_constraint(None, 'stage_evaluation_workspace', type_='foreignkey')
    op.drop_constraint(None, 'stage_evaluation_workspace', type_='foreignkey')
    op.drop_constraint(None, 'stage_evaluation_workspace', type_='foreignkey')
    op.create_foreign_key(op.f('stage_evaluation_workspace_createdByMemberId_fkey'), 'stage_evaluation_workspace', 'member', ['createdByMemberId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('stage_evaluation_workspace_organizationId_fkey'), 'stage_evaluation_workspace', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('stage_evaluation_workspace_stageId_fkey'), 'stage_evaluation_workspace', 'pipeline_stage', ['stageId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_stage_evaluation_workspace_stage', 'stage_evaluation_workspace', type_='unique')
    op.drop_constraint('uq_stage_evaluation_workspace_org_stage', 'stage_evaluation_workspace', type_='unique')
    op.drop_index(op.f('ix_stage_evaluation_workspace_stageId'), table_name='stage_evaluation_workspace')
    op.drop_index(op.f('ix_stage_evaluation_workspace_organizationId'), table_name='stage_evaluation_workspace')
    op.drop_index('ix_stage_evaluation_workspace_org_stage', table_name='stage_evaluation_workspace')
    op.drop_index(op.f('ix_stage_evaluation_workspace_createdByMemberId'), table_name='stage_evaluation_workspace')
    op.create_index(op.f('stage_evaluation_workspace_stageId_key'), 'stage_evaluation_workspace', ['stageId'], unique=True)
    op.create_index(op.f('stage_evaluation_workspace_stageId_idx'), 'stage_evaluation_workspace', ['stageId'], unique=False)
    op.create_index(op.f('stage_evaluation_workspace_organizationId_stageId_key'), 'stage_evaluation_workspace', ['organizationId', 'stageId'], unique=True)
    op.create_index(op.f('stage_evaluation_workspace_organizationId_stageId_idx'), 'stage_evaluation_workspace', ['organizationId', 'stageId'], unique=False)
    op.create_index(op.f('stage_evaluation_workspace_organizationId_idx'), 'stage_evaluation_workspace', ['organizationId'], unique=False)
    op.create_index(op.f('stage_evaluation_workspace_createdByMemberId_idx'), 'stage_evaluation_workspace', ['createdByMemberId'], unique=False)
    op.drop_constraint(None, 'stage_evaluation_category', type_='foreignkey')
    op.drop_constraint(None, 'stage_evaluation_category', type_='foreignkey')
    op.create_foreign_key(op.f('stage_evaluation_category_stageId_fkey'), 'stage_evaluation_category', 'pipeline_stage', ['stageId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('stage_evaluation_category_organizationId_fkey'), 'stage_evaluation_category', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_stage_evaluation_category_order', 'stage_evaluation_category', type_='unique')
    op.drop_index(op.f('ix_stage_evaluation_category_stageId'), table_name='stage_evaluation_category')
    op.drop_index(op.f('ix_stage_evaluation_category_organizationId'), table_name='stage_evaluation_category')
    op.drop_index('ix_stage_evaluation_category_org_stage', table_name='stage_evaluation_category')
    op.create_index(op.f('stage_evaluation_category_stageId_order_key'), 'stage_evaluation_category', ['stageId', 'order'], unique=True)
    op.create_index(op.f('stage_evaluation_category_stageId_idx'), 'stage_evaluation_category', ['stageId'], unique=False)
    op.create_index(op.f('stage_evaluation_category_organizationId_stageId_idx'), 'stage_evaluation_category', ['organizationId', 'stageId'], unique=False)
    op.create_index(op.f('stage_evaluation_category_organizationId_idx'), 'stage_evaluation_category', ['organizationId'], unique=False)
    op.drop_constraint('public_holiday_master_date_name_location_key', 'public_holiday_master', type_='unique')
    op.create_index(op.f('public_holiday_master_date_name_location_key'), 'public_holiday_master', ['date', 'name', 'location'], unique=True)
    op.drop_column('public_holiday_master', 'isHoliday')
    op.drop_constraint(None, 'pipeline_stage', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_stage', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_stage', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_stage_organizationId_fkey'), 'pipeline_stage', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('pipeline_stage_jobPostingId_fkey'), 'pipeline_stage', 'job_posting', ['jobPostingId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_pipeline_stage_order', 'pipeline_stage', type_='unique')
    op.drop_constraint('uq_pipeline_stage_job_slug', 'pipeline_stage', type_='unique')
    op.drop_index(op.f('ix_pipeline_stage_stageId'), table_name='pipeline_stage')
    op.drop_index(op.f('ix_pipeline_stage_organizationId'), table_name='pipeline_stage')
    op.drop_index(op.f('ix_pipeline_stage_jobPostingId'), table_name='pipeline_stage')
    op.create_index(op.f('pipeline_stage_organizationId_idx'), 'pipeline_stage', ['organizationId'], unique=False)
    op.create_index(op.f('pipeline_stage_jobPostingId_order_key'), 'pipeline_stage', ['jobPostingId', 'order'], unique=True)
    op.create_index(op.f('pipeline_stage_jobPostingId_idx'), 'pipeline_stage', ['jobPostingId'], unique=False)
    op.drop_column('pipeline_stage', 'slug')
    op.drop_column('pipeline_stage', 'stageId')
    op.create_foreign_key(op.f('leave_type_organizationId_fkey'), 'leave_type', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('leave_type_organizationId_name_key', 'leave_type', type_='unique')
    op.create_index(op.f('leave_type_organizationId_name_key'), 'leave_type', ['organizationId', 'name'], unique=True)
    op.drop_constraint(None, 'leave_request', type_='foreignkey')
    op.drop_constraint(None, 'leave_request', type_='foreignkey')
    op.drop_constraint(None, 'leave_request', type_='foreignkey')
    op.create_foreign_key(op.f('leave_request_organizationId_fkey'), 'leave_request', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('leave_request_memberId_fkey'), 'leave_request', 'member', ['memberId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('leave_request_leaveTypeId_fkey'), 'leave_request', 'leave_type', ['leaveTypeId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('leave_request_approvedById_fkey'), 'leave_request', 'member', ['approvedById'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint(None, 'leave_balance', type_='foreignkey')
    op.drop_constraint(None, 'leave_balance', type_='foreignkey')
    op.create_foreign_key(op.f('leave_balance_organizationId_fkey'), 'leave_balance', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('leave_balance_memberId_fkey'), 'leave_balance', 'member', ['memberId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('leave_balance_leaveTypeId_fkey'), 'leave_balance', 'leave_type', ['leaveTypeId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('leave_balance_org_member_type_year_key', 'leave_balance', type_='unique')
    op.create_index(op.f('leave_balance_organizationId_memberId_leaveTypeId_year_key'), 'leave_balance', ['organizationId', 'memberId', 'leaveTypeId', 'year'], unique=True)
    op.drop_constraint(None, 'job_posting', type_='foreignkey')
    op.create_foreign_key(op.f('job_posting_organizationId_fkey'), 'job_posting', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_job_posting_org_slug', 'job_posting', type_='unique')
    op.drop_index(op.f('ix_job_posting_status'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_organizationId'), table_name='job_posting')
    op.create_index(op.f('job_posting_organizationId_status_idx'), 'job_posting', ['organizationId', 'status'], unique=False)
    op.create_index(op.f('job_posting_organizationId_idx'), 'job_posting', ['organizationId'], unique=False)
    op.drop_column('job_posting', 'slug')
    op.create_foreign_key(op.f('holiday_organizationId_fkey'), 'holiday', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'departmentMember', type_='foreignkey')
    op.drop_constraint(None, 'departmentMember', type_='foreignkey')
    op.create_foreign_key(op.f('departmentMember_departmentId_fkey'), 'departmentMember', 'department', ['departmentId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('departmentMember_memberId_fkey'), 'departmentMember', 'member', ['memberId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('departmentMember_departmentId_memberId_key', 'departmentMember', type_='unique')
    op.create_index(op.f('departmentMember_departmentId_memberId_key'), 'departmentMember', ['departmentId', 'memberId'], unique=True)
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.create_foreign_key(op.f('department_parentDepartmentId_fkey'), 'department', 'department', ['parentDepartmentId'], ['id'])
    op.drop_constraint(None, 'candidate_application', type_='foreignkey')
    op.drop_constraint(None, 'candidate_application', type_='foreignkey')
    op.drop_constraint(None, 'candidate_application', type_='foreignkey')
    op.drop_constraint(None, 'candidate_application', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_application_jobPostingId_fkey'), 'candidate_application', 'job_posting', ['jobPostingId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('candidate_application_organizationId_fkey'), 'candidate_application', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('candidate_application_candidateId_fkey'), 'candidate_application', 'candidate', ['candidateId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('candidate_application_pipelineStageId_fkey'), 'candidate_application', 'pipeline_stage', ['pipelineStageId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint('uq_candidate_job_application', 'candidate_application', type_='unique')
    op.drop_index(op.f('ix_candidate_application_pipelineStageId'), table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_organizationId'), table_name='candidate_application')
    op.drop_index('ix_candidate_application_org_stage', table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_jobPostingId'), table_name='candidate_application')
    op.create_index(op.f('candidate_application_pipelineStageId_idx'), 'candidate_application', ['pipelineStageId'], unique=False)
    op.create_index(op.f('candidate_application_organizationId_pipelineStageId_idx'), 'candidate_application', ['organizationId', 'pipelineStageId'], unique=False)
    op.create_index(op.f('candidate_application_organizationId_idx'), 'candidate_application', ['organizationId'], unique=False)
    op.create_index(op.f('candidate_application_jobPostingId_idx'), 'candidate_application', ['jobPostingId'], unique=False)
    op.create_index(op.f('candidate_application_candidateId_jobPostingId_key'), 'candidate_application', ['candidateId', 'jobPostingId'], unique=True)
    op.drop_column('candidate_application', 'rating')
    op.drop_column('candidate_application', 'internalNotes')
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_userId_fkey'), 'candidate', 'user', ['userId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('candidate_organizationId_fkey'), 'candidate', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('uq_candidate_org_email', 'candidate', type_='unique')
    op.drop_index(op.f('ix_candidate_userId'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_organizationId'), table_name='candidate')
    op.create_index(op.f('candidate_userId_idx'), 'candidate', ['userId'], unique=False)
    op.create_index(op.f('candidate_organizationId_idx'), 'candidate', ['organizationId'], unique=False)
    op.create_index(op.f('candidate_organizationId_email_key'), 'candidate', ['organizationId', 'email'], unique=True)
    op.drop_column('candidate', 'totalExperience')
    op.drop_column('candidate', 'currentTitle')
    op.drop_column('candidate', 'currentCompany')
    op.drop_column('candidate', 'portfolioUrl')
    op.drop_constraint(None, 'attendanceWorkLog', type_='foreignkey')
    op.create_foreign_key(op.f('attendanceWorkLog_attendanceRecordId_fkey'), 'attendanceWorkLog', 'attendanceRecord', ['attendanceRecordId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('attendanceRecord_employeeId_date_key', 'attendanceRecord', type_='unique')
    op.create_index(op.f('attendanceRecord_employeeId_date_key'), 'attendanceRecord', ['employeeId', 'date'], unique=True)
    op.drop_constraint(None, 'application_stage_history', type_='foreignkey')
    op.drop_constraint(None, 'application_stage_history', type_='foreignkey')
    op.drop_constraint(None, 'application_stage_history', type_='foreignkey')
    op.drop_constraint(None, 'application_stage_history', type_='foreignkey')
    op.drop_constraint(None, 'application_stage_history', type_='foreignkey')
    op.create_foreign_key(op.f('application_stage_history_toStageId_fkey'), 'application_stage_history', 'pipeline_stage', ['toStageId'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('application_stage_history_movedByMemberId_fkey'), 'application_stage_history', 'member', ['movedByMemberId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('application_stage_history_applicationId_fkey'), 'application_stage_history', 'candidate_application', ['applicationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('application_stage_history_fromStageId_fkey'), 'application_stage_history', 'pipeline_stage', ['fromStageId'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(op.f('application_stage_history_organizationId_fkey'), 'application_stage_history', 'organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_application_stage_history_toStageId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_organizationId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_movedByMemberId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_fromStageId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_applicationId'), table_name='application_stage_history')
    op.create_index(op.f('application_stage_history_toStageId_idx'), 'application_stage_history', ['toStageId'], unique=False)
    op.create_index(op.f('application_stage_history_organizationId_idx'), 'application_stage_history', ['organizationId'], unique=False)
    op.create_index(op.f('application_stage_history_movedByMemberId_idx'), 'application_stage_history', ['movedByMemberId'], unique=False)
    op.create_index(op.f('application_stage_history_fromStageId_idx'), 'application_stage_history', ['fromStageId'], unique=False)
    op.create_index(op.f('application_stage_history_applicationId_idx'), 'application_stage_history', ['applicationId'], unique=False)
    op.drop_index('project_task_projectId_idx', table_name='project_task')
    op.drop_table('project_task')
    op.drop_index('project_member_projectId_idx', table_name='project_member')
    op.drop_index('project_member_memberId_idx', table_name='project_member')
    op.drop_table('project_member')
    op.drop_index('team_member_teamId_idx', table_name='team_member')
    op.drop_index('team_member_memberId_idx', table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_stage_event_participant_memberId'), table_name='stage_event_participant')
    op.drop_index(op.f('ix_stage_event_participant_eventId'), table_name='stage_event_participant')
    op.drop_table('stage_event_participant')
    op.drop_index(op.f('ix_requisition_approval_requisitionId'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_organizationId'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_decision'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_approverId'), table_name='requisition_approval')
    op.drop_table('requisition_approval')
    op.drop_index('project_teamId_idx', table_name='project')
    op.drop_index('project_organizationId_status_idx', table_name='project')
    op.drop_index('project_organizationId_idx', table_name='project')
    op.drop_index('project_organizationId_deletedAt_idx', table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_interview_feedback_organizationId'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_memberId'), table_name='interview_feedback')
    op.drop_index(op.f('ix_interview_feedback_eventId'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    op.drop_index('team_organizationId_status_idx', table_name='team')
    op.drop_index('team_organizationId_idx', table_name='team')
    op.drop_index('team_leadMemberId_idx', table_name='team')
    op.drop_index('team_departmentId_idx', table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_stage_event_teamId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_status'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_stageId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_organizationId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_createdByMemberId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_applicationId'), table_name='stage_event')
    op.drop_table('stage_event')
    op.drop_index(op.f('ix_offer_letter_status'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_organizationId'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_createdByMemberId'), table_name='offer_letter')
    op.drop_index(op.f('ix_offer_letter_applicationId'), table_name='offer_letter')
    op.drop_table('offer_letter')
    op.drop_index(op.f('ix_job_requisition_status'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_raisedById'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_organizationId'), table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_status', table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_raised_by', table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_departmentId'), table_name='job_requisition')
    op.drop_table('job_requisition')
    op.drop_index(op.f('ix_hiring_team_member_memberId'), table_name='hiring_team_member')
    op.drop_index(op.f('ix_hiring_team_member_hiringTeamId'), table_name='hiring_team_member')
    op.drop_table('hiring_team_member')
    op.drop_index('asset_maintenance_log_status_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_serviceDate_idx', table_name='asset_maintenance_log')
    op.drop_index('asset_maintenance_log_assetId_idx', table_name='asset_maintenance_log')
    op.drop_table('asset_maintenance_log')
    op.drop_index('asset_assignment_returnDate_idx', table_name='asset_assignment')
    op.drop_index('asset_assignment_memberId_idx', table_name='asset_assignment')
    op.drop_index('asset_assignment_assetId_idx', table_name='asset_assignment')
    op.drop_table('asset_assignment')
    op.drop_index(op.f('ix_hiring_team_stageId'), table_name='hiring_team')
    op.drop_index(op.f('ix_hiring_team_organizationId'), table_name='hiring_team')
    op.drop_index(op.f('ix_hiring_team_jobPostingId'), table_name='hiring_team')
    op.drop_index('hiring_team_organizationId_isActive_idx', table_name='hiring_team')
    op.drop_index('hiring_team_organizationId_idx', table_name='hiring_team')
    op.drop_index('hiring_team_jobPostingId_idx', table_name='hiring_team')
    op.drop_table('hiring_team')
    op.drop_index('asset_unit_status_idx', table_name='asset_unit')
    op.drop_index('asset_unit_holder_idx', table_name='asset_unit')
    op.drop_index('asset_unit_asset_idx', table_name='asset_unit')
    op.drop_table('asset_unit')
    op.drop_index('asset_custom_field_def_idx', table_name='asset_custom_field_value')
    op.drop_index('asset_custom_field_asset_idx', table_name='asset_custom_field_value')
    op.drop_index('asset_custom_field_asset_def_idx', table_name='asset_custom_field_value')
    op.drop_table('asset_custom_field_value')
    op.drop_index(op.f('ix_asset_id_definitions_organizationId'), table_name='asset_id_definitions')
    op.drop_table('asset_id_definitions')
    op.drop_index('asset_cat_field_def_cat_idx', table_name='asset_category_field_definition')
    op.drop_table('asset_category_field_definition')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_organization_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_monthly_plans_user_id'), table_name='monthly_plans')
    op.drop_index(op.f('ix_monthly_plans_organization_id'), table_name='monthly_plans')
    op.drop_table('monthly_plans')
    op.drop_index('asset_category_def_org_name_idx', table_name='asset_category_definition')
    op.drop_index('asset_category_def_org_idx', table_name='asset_category_definition')
    op.drop_table('asset_category_definition')
    op.drop_index('asset_organizationId_status_idx', table_name='asset')
    op.drop_index('asset_organizationId_idx', table_name='asset')
    op.drop_index('asset_organizationId_deletedAt_idx', table_name='asset')
    op.drop_index('asset_organizationId_category_idx', table_name='asset')
    op.drop_index('asset_organizationId_assetCode_idx', table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
