"""add ats models

Revision ID: 3c3beaa89523
Revises: a55397403e29
Create Date: 2026-05-07 22:44:36.979030
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3beaa89523'
down_revision: Union[str, None] = 'a55397403e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_holiday_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), server_default='IN-TN', nullable=False),
    sa.Column('isHoliday', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'name', 'location', name='public_holiday_master_date_name_location_key')
    )
    op.create_index('public_holiday_master_year_location_idx', 'public_holiday_master', ['year', 'location'], unique=False)
    op.create_table('candidate',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('userId', sa.String(length=36), nullable=True),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linkedinUrl', sa.String(), nullable=True),
    sa.Column('resumeUrl', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'email', name='uq_candidate_org_email')
    )
    op.create_index(op.f('ix_candidate_organizationId'), 'candidate', ['organizationId'], unique=False)
    op.create_index(op.f('ix_candidate_userId'), 'candidate', ['userId'], unique=False)
    op.create_table('job_posting',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='jobpostingstatus'), nullable=False),
    sa.Column('publishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posting_organizationId'), 'job_posting', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_posting_status'), 'job_posting', ['status'], unique=False)
    op.create_table('pipeline_stage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('isDefault', sa.Boolean(), nullable=False),
    sa.Column('isFinal', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jobPostingId', 'order', name='uq_pipeline_stage_order')
    )
    op.create_index(op.f('ix_pipeline_stage_jobPostingId'), 'pipeline_stage', ['jobPostingId'], unique=False)
    op.create_index(op.f('ix_pipeline_stage_organizationId'), 'pipeline_stage', ['organizationId'], unique=False)
    op.create_table('candidate_application',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('candidateId', sa.String(length=36), nullable=False),
    sa.Column('jobPostingId', sa.String(length=36), nullable=False),
    sa.Column('pipelineStageId', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('LINKEDIN', 'REFERRAL', 'COMPANY_WEBSITE', 'JOB_BOARD', 'DIRECT', 'OTHER', name='applicationsource'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('appliedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastActivityAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jobPostingId'], ['job_posting.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipelineStageId'], ['pipeline_stage.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidateId', 'jobPostingId', name='uq_candidate_job_application')
    )
    op.create_index(op.f('ix_candidate_application_jobPostingId'), 'candidate_application', ['jobPostingId'], unique=False)
    op.create_index('ix_candidate_application_org_stage', 'candidate_application', ['organizationId', 'pipelineStageId'], unique=False)
    op.create_index(op.f('ix_candidate_application_organizationId'), 'candidate_application', ['organizationId'], unique=False)
    op.create_index(op.f('ix_candidate_application_pipelineStageId'), 'candidate_application', ['pipelineStageId'], unique=False)
    op.create_table('application_stage_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('applicationId', sa.String(length=36), nullable=False),
    sa.Column('fromStageId', sa.String(length=36), nullable=True),
    sa.Column('toStageId', sa.String(length=36), nullable=False),
    sa.Column('movedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicationId'], ['candidate_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fromStageId'], ['pipeline_stage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['toStageId'], ['pipeline_stage.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_stage_history_applicationId'), 'application_stage_history', ['applicationId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_fromStageId'), 'application_stage_history', ['fromStageId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_movedByMemberId'), 'application_stage_history', ['movedByMemberId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_organizationId'), 'application_stage_history', ['organizationId'], unique=False)
    op.create_index(op.f('ix_application_stage_history_toStageId'), 'application_stage_history', ['toStageId'], unique=False)
    op.drop_index(op.f('job_requisition_departmentId_idx'), table_name='job_requisition')
    op.drop_index(op.f('job_requisition_hiringManagerId_idx'), table_name='job_requisition')
    op.drop_index(op.f('job_requisition_organizationId_idx'), table_name='job_requisition')
    op.drop_index(op.f('job_requisition_organizationId_status_idx'), table_name='job_requisition')
    op.drop_table('job_requisition_approval')
    op.drop_table('job_requisition')
    op.add_column(
    'holiday',
    sa.Column(
        'isHoliday',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holiday', 'isHoliday')
    op.create_table('job_requisition_approval',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('requisitionId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('approverId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('step', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approverId'], ['member.id'], name=op.f('job_requisition_approval_approverId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], name=op.f('job_requisition_approval_requisitionId_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_requisition_approval_pkey'))
    )
    op.create_index(op.f('job_requisition_approval_requisitionId_idx'), 'job_requisition_approval', ['requisitionId'], unique=False)
    op.create_index(op.f('job_requisition_approval_approverId_idx'), 'job_requisition_approval', ['approverId'], unique=False)
    op.create_table('job_requisition',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organizationId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('departmentId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('hiringManagerId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('requiredSkills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('headcount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('targetDate', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('currentApprovalStep', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('rejectionReason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('jobPostingUrl', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('createdById', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['createdById'], ['member.id'], name=op.f('job_requisition_createdById_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], name=op.f('job_requisition_departmentId_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hiringManagerId'], ['member.id'], name=op.f('job_requisition_hiringManagerId_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_requisition_pkey'))
    )
    op.create_index(op.f('job_requisition_organizationId_status_idx'), 'job_requisition', ['organizationId', 'status'], unique=False)
    op.create_index(op.f('job_requisition_organizationId_idx'), 'job_requisition', ['organizationId'], unique=False)
    op.create_index(op.f('job_requisition_hiringManagerId_idx'), 'job_requisition', ['hiringManagerId'], unique=False)
    op.create_index(op.f('job_requisition_departmentId_idx'), 'job_requisition', ['departmentId'], unique=False)
    op.drop_index(op.f('ix_application_stage_history_toStageId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_organizationId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_movedByMemberId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_fromStageId'), table_name='application_stage_history')
    op.drop_index(op.f('ix_application_stage_history_applicationId'), table_name='application_stage_history')
    op.drop_table('application_stage_history')
    op.drop_index(op.f('ix_candidate_application_pipelineStageId'), table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_organizationId'), table_name='candidate_application')
    op.drop_index('ix_candidate_application_org_stage', table_name='candidate_application')
    op.drop_index(op.f('ix_candidate_application_jobPostingId'), table_name='candidate_application')
    op.drop_table('candidate_application')
    op.drop_index(op.f('ix_pipeline_stage_organizationId'), table_name='pipeline_stage')
    op.drop_index(op.f('ix_pipeline_stage_jobPostingId'), table_name='pipeline_stage')
    op.drop_table('pipeline_stage')
    op.drop_index(op.f('ix_job_posting_status'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_organizationId'), table_name='job_posting')
    op.drop_table('job_posting')
    op.drop_index(op.f('ix_candidate_userId'), table_name='candidate')
    op.drop_index(op.f('ix_candidate_organizationId'), table_name='candidate')
    op.drop_table('candidate')
    op.drop_index('public_holiday_master_year_location_idx', table_name='public_holiday_master')
    op.drop_table('public_holiday_master')
    # ### end Alembic commands ###
