"""asset_id definitions table

Revision ID: 40e3ade9ac5a
Revises: e9f8b4a7d3c2
Create Date: 2026-05-13 22:53:18.770364
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '40e3ade9ac5a'
down_revision: Union[str, None] = 'e9f8b4a7d3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_id_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('assetIdName', sa.String(length=120), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id_definitions_organizationId'), 'asset_id_definitions', ['organizationId'], unique=False)
    

def downgrade() -> None:
    op.drop_index(op.f('ix_asset_id_definitions_organizationId'), table_name='asset_id_definitions')
    op.drop_table('asset_id_definitions')
    