"""remove_field_endDate

Revision ID: 58d4b9ca0d21
Revises: f43cf5b85a2b
Create Date: 2026-05-11 14:59:41.416108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d4b9ca0d21'
down_revision: Union[str, None] = 'f43cf5b85a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_stage_org_slug'), table_name='pipeline_stage')
    op.drop_constraint(op.f('uq_pipeline_stage_org_slug'), 'pipeline_stage', type_='unique')
    op.drop_column('pipeline_stage', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_stage', sa.Column('slug', sa.VARCHAR(length=160), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_pipeline_stage_org_slug'), 'pipeline_stage', ['organizationId', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipeline_stage_org_slug'), 'pipeline_stage', ['organizationId', 'slug'], unique=False)
    # ### end Alembic commands ###
