"""sync

Revision ID: 5cab7470aedf
Revises: aa4d25d3a4a8
Create Date: 2026-05-03 21:37:44.301758
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cab7470aedf'
down_revision: Union[str, None] = 'aa4d25d3a4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
   
    op.drop_index(op.f('Member_organizationId_idx'), table_name='Member')
    op.drop_index(op.f('Member_organizationId_userId_key'), table_name='Member')
    op.drop_index(op.f('Member_userId_idx'), table_name='Member')
    op.create_index('member_organizationId_idx', 'Member', ['organizationId'], unique=False)
    op.create_unique_constraint('member_organizationId_userId_key', 'Member', ['organizationId', 'userId'])
    op.create_index('member_userId_idx', 'Member', ['userId'], unique=False)
    op.drop_constraint(op.f('Member_organizationId_roleId_fkey'), 'Member', type_='foreignkey')
    op.drop_constraint(op.f('Member_userId_fkey'), 'Member', type_='foreignkey')
    op.drop_constraint(op.f('Member_organizationId_fkey'), 'Member', type_='foreignkey')
    op.create_foreign_key(None, 'Member', 'Role', ['organizationId', 'roleId'], ['organizationId', 'id'])
    op.create_foreign_key(None, 'Member', 'user', ['userId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Member', 'Organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('Organization_slug_key'), table_name='Organization')
    op.create_unique_constraint('organization_slug_key', 'Organization', ['slug'])
    op.create_index('role_organizationId_idx', 'Role', ['organizationId'], unique=False)
    op.create_unique_constraint(None, 'Role', ['organizationId', 'id'])
    op.create_unique_constraint(None, 'Role', ['organizationId', 'name'])
    op.drop_constraint(op.f('Role_organizationId_fkey'), 'Role', type_='foreignkey')
    op.create_foreign_key(None, 'Role', 'Organization', ['organizationId'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('account_userId_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'user', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('session_token_key'), table_name='session')
    op.create_unique_constraint('session_token_key', 'session', ['token'])
    op.drop_constraint(op.f('session_userId_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'user', ['userId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('user_email_key'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('user_email_key'), 'user', ['email'], unique=True)
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_userId_fkey'), 'session', 'user', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('session_token_key', 'session', type_='unique')
    op.create_index(op.f('session_token_key'), 'session', ['token'], unique=True)
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_userId_fkey'), 'account', 'user', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Role', type_='foreignkey')
    op.create_foreign_key(op.f('Role_organizationId_fkey'), 'Role', 'Organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'Role', type_='unique')
    op.drop_constraint(None, 'Role', type_='unique')
    op.drop_index('role_organizationId_idx', table_name='Role')
    op.create_index(op.f('Role_organizationId_name_key'), 'Role', ['organizationId', 'name'], unique=True)
    op.create_index(op.f('Role_organizationId_idx'), 'Role', ['organizationId'], unique=False)
    op.create_index(op.f('Role_organizationId_id_key'), 'Role', ['organizationId', 'id'], unique=True)
    op.drop_constraint('organization_slug_key', 'Organization', type_='unique')
    op.create_index(op.f('Organization_slug_key'), 'Organization', ['slug'], unique=True)
    op.drop_constraint(None, 'Member', type_='foreignkey')
    op.drop_constraint(None, 'Member', type_='foreignkey')
    op.drop_constraint(None, 'Member', type_='foreignkey')
    op.create_foreign_key(op.f('Member_organizationId_fkey'), 'Member', 'Organization', ['organizationId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('Member_userId_fkey'), 'Member', 'user', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('Member_organizationId_roleId_fkey'), 'Member', 'Role', ['organizationId', 'roleId'], ['organizationId', 'id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index('member_userId_idx', table_name='Member')
    op.drop_constraint('member_organizationId_userId_key', 'Member', type_='unique')
    op.drop_index('member_organizationId_idx', table_name='Member')
    op.create_index(op.f('Member_userId_idx'), 'Member', ['userId'], unique=False)
    op.create_index(op.f('Member_organizationId_userId_key'), 'Member', ['organizationId', 'userId'], unique=True)
    op.create_index(op.f('Member_organizationId_idx'), 'Member', ['organizationId'], unique=False)
    
    # ### end Alembic commands ###
