"""add department module

Revision ID: 719a71a8fb80
Revises: a8c5d7e9f102
Create Date: 2026-05-07 14:32:24.385380
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '719a71a8fb80'
down_revision: Union[str, None] = 'a8c5d7e9f102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parentDepartmentId', sa.String(length=36), nullable=True),
    sa.Column('headMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='ACTIVE', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['headMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parentDepartmentId'], ['department.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('department_headMemberId_idx', 'department', ['headMemberId'], unique=False)
    op.create_index('department_organizationId_idx', 'department', ['organizationId'], unique=False)
    op.create_index('department_organizationId_status_idx', 'department', ['organizationId', 'status'], unique=False)
    op.create_index('department_parentDepartmentId_idx', 'department', ['parentDepartmentId'], unique=False)
    op.create_table('departmentMember',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('joinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departmentId', 'memberId', name='departmentMember_departmentId_memberId_key')
    )
    op.create_index('departmentMember_departmentId_idx', 'departmentMember', ['departmentId'], unique=False)
    op.create_index('departmentMember_memberId_idx', 'departmentMember', ['memberId'], unique=False)
    op.create_table('job_requisition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=True),
    sa.Column('hiringManagerId', sa.String(length=36), nullable=True),
    sa.Column('requiredSkills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('targetDate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('currentApprovalStep', sa.String(length=32), nullable=True),
    sa.Column('rejectionReason', sa.Text(), nullable=True),
    sa.Column('jobPostingUrl', sa.String(length=512), nullable=True),
    sa.Column('createdById', sa.String(length=36), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['createdById'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hiringManagerId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_requisition_departmentId_idx', 'job_requisition', ['departmentId'], unique=False)
    op.create_index('job_requisition_hiringManagerId_idx', 'job_requisition', ['hiringManagerId'], unique=False)
    op.create_index('job_requisition_organizationId_idx', 'job_requisition', ['organizationId'], unique=False)
    op.create_index('job_requisition_organizationId_status_idx', 'job_requisition', ['organizationId', 'status'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('leadMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leadMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizationId', 'departmentId', 'name', name='team_organizationId_departmentId_name_key')
    )
    op.create_index('team_departmentId_idx', 'team', ['departmentId'], unique=False)
    op.create_index('team_leadMemberId_idx', 'team', ['leadMemberId'], unique=False)
    op.create_index('team_organizationId_idx', 'team', ['organizationId'], unique=False)
    op.create_index('team_organizationId_status_idx', 'team', ['organizationId', 'status'], unique=False)
    op.create_table('job_requisition_approval',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=False),
    sa.Column('approverId', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approverId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('job_requisition_approval_approverId_idx', 'job_requisition_approval', ['approverId'], unique=False)
    op.create_index('job_requisition_approval_requisitionId_idx', 'job_requisition_approval', ['requisitionId'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clientName', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budgetedHours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('endDate', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='ACTIVE', nullable=False),
    sa.Column('billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_organizationId_deletedAt_idx', 'project', ['organizationId', 'deletedAt'], unique=False)
    op.create_index('project_organizationId_idx', 'project', ['organizationId'], unique=False)
    op.create_index('project_organizationId_status_idx', 'project', ['organizationId', 'status'], unique=False)
    op.create_index('project_teamId_idx', 'project', ['teamId'], unique=False)
    op.create_table('team_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teamId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('joinedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teamId', 'memberId', name='team_member_teamId_memberId_key')
    )
    op.create_index('team_member_memberId_idx', 'team_member', ['memberId'], unique=False)
    op.create_index('team_member_teamId_idx', 'team_member', ['teamId'], unique=False)
    op.create_table('project_member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=36), nullable=False),
    sa.Column('memberId', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('allocatedHours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projectId', 'memberId', name='project_member_projectId_memberId_key')
    )
    op.create_index('project_member_memberId_idx', 'project_member', ['memberId'], unique=False)
    op.create_index('project_member_projectId_idx', 'project_member', ['projectId'], unique=False)
    op.create_table('project_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectId', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assignedMemberId', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='TODO', nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignedMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('project_task_assignedMemberId_idx', 'project_task', ['assignedMemberId'], unique=False)
    op.create_index('project_task_projectId_idx', 'project_task', ['projectId'], unique=False)
    op.create_index('project_task_projectId_status_idx', 'project_task', ['projectId', 'status'], unique=False)
    op.drop_index(op.f('public_holiday_master_year_location_idx'), table_name='public_holiday_master')
    op.drop_table('public_holiday_master')
    op.drop_column('holiday', 'isHoliday')
    op.create_foreign_key(None, 'member', 'role', ['organizationId', 'roleId'], ['organizationId', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.add_column('holiday', sa.Column('isHoliday', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_table('public_holiday_master',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=50), server_default=sa.text("'IN-TN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('public_holiday_master_pkey')),
    sa.UniqueConstraint('date', 'name', 'location', name=op.f('public_holiday_master_date_name_location_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('public_holiday_master_year_location_idx'), 'public_holiday_master', ['year', 'location'], unique=False)
    op.drop_index('project_task_projectId_status_idx', table_name='project_task')
    op.drop_index('project_task_projectId_idx', table_name='project_task')
    op.drop_index('project_task_assignedMemberId_idx', table_name='project_task')
    op.drop_table('project_task')
    op.drop_index('project_member_projectId_idx', table_name='project_member')
    op.drop_index('project_member_memberId_idx', table_name='project_member')
    op.drop_table('project_member')
    op.drop_index('team_member_teamId_idx', table_name='team_member')
    op.drop_index('team_member_memberId_idx', table_name='team_member')
    op.drop_table('team_member')
    op.drop_index('project_teamId_idx', table_name='project')
    op.drop_index('project_organizationId_status_idx', table_name='project')
    op.drop_index('project_organizationId_idx', table_name='project')
    op.drop_index('project_organizationId_deletedAt_idx', table_name='project')
    op.drop_table('project')
    op.drop_index('job_requisition_approval_requisitionId_idx', table_name='job_requisition_approval')
    op.drop_index('job_requisition_approval_approverId_idx', table_name='job_requisition_approval')
    op.drop_table('job_requisition_approval')
    op.drop_index('team_organizationId_status_idx', table_name='team')
    op.drop_index('team_organizationId_idx', table_name='team')
    op.drop_index('team_leadMemberId_idx', table_name='team')
    op.drop_index('team_departmentId_idx', table_name='team')
    op.drop_table('team')
    op.drop_index('job_requisition_organizationId_status_idx', table_name='job_requisition')
    op.drop_index('job_requisition_organizationId_idx', table_name='job_requisition')
    op.drop_index('job_requisition_hiringManagerId_idx', table_name='job_requisition')
    op.drop_index('job_requisition_departmentId_idx', table_name='job_requisition')
    op.drop_table('job_requisition')
    op.drop_index('departmentMember_memberId_idx', table_name='departmentMember')
    op.drop_index('departmentMember_departmentId_idx', table_name='departmentMember')
    op.drop_table('departmentMember')
    op.drop_index('department_parentDepartmentId_idx', table_name='department')
    op.drop_index('department_organizationId_status_idx', table_name='department')
    op.drop_index('department_organizationId_idx', table_name='department')
    op.drop_index('department_headMemberId_idx', table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
