"""check

Revision ID: 7a17b0ce3f01
Revises: ad1e40baa235
Create Date: 2026-05-04 12:06:14.920147
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a17b0ce3f01'
down_revision: Union[str, None] = 'ad1e40baa235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('member_organizationid_idx'), table_name='member')
    op.drop_index(op.f('member_userid_idx'), table_name='member')
    op.drop_index(op.f('Role_organizationId_id_key'), table_name='role')
    op.drop_index(op.f('Role_organizationId_idx'), table_name='role')
    op.drop_index(op.f('Role_organizationId_name_key'), table_name='role')
    op.drop_index(op.f('role_organizationid_idx'), table_name='role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('role_organizationid_idx'), 'role', ['organizationId'], unique=False)
    op.create_index(op.f('Role_organizationId_name_key'), 'role', ['organizationId', 'name'], unique=True)
    op.create_index(op.f('Role_organizationId_idx'), 'role', ['organizationId'], unique=False)
    op.create_index(op.f('Role_organizationId_id_key'), 'role', ['organizationId', 'id'], unique=True)
    op.create_index(op.f('member_userid_idx'), 'member', ['userId'], unique=False)
    op.create_index(op.f('member_organizationid_idx'), 'member', ['organizationId'], unique=False)
    # ### end Alembic commands ###
