"""add_completed_at_to_pipeline_stage

Revision ID: 9bc8279279dd
Revises: b4c6d8e0f2a1
Create Date: 2026-05-20 09:24:16.068100
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc8279279dd'
down_revision: Union[str, None] = 'b4c6d8e0f2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_category_definition', sa.Column('asset_code', sa.String(length=120), nullable=True))
    op.alter_column('candidate_application_note', 'createdAt',
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_application_note', 'updatedAt',
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_feedback_value', 'createdAt',
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_feedback_value', 'updatedAt',
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('pipeline_stage', sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_stage', 'completedAt')
    op.alter_column('interview_feedback_value', 'updatedAt',
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('interview_feedback_value', 'createdAt',
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_application_note', 'updatedAt',
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidate_application_note', 'createdAt',
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('asset_category_definition', 'asset_code')
    # ### end Alembic commands ###
