"""sync_team_models

Revision ID: 9d505aa3efc3
Revises: c4d5e6f7a8b0
Create Date: 2026-06-04 16:48:07.569410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d505aa3efc3'
down_revision: Union[str, None] = 'c4d5e6f7a8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('project_teamId_idx'), table_name='project')
    op.drop_constraint(op.f('project_teamId_fkey'), 'project', type_='foreignkey')
    op.drop_column('project', 'teamId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('teamId', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('project_teamId_fkey'), 'project', 'team', ['teamId'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('project_teamId_idx'), 'project', ['teamId'], unique=False)
    # ### end Alembic commands ###
