"""add_access_control_tables

Revision ID: eda69bd912f2
Revises: b5f6c2e4a901
Create Date: 2026-05-27 16:23:44.747852
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda69bd912f2'
down_revision: Union[str, None] = 'b5f6c2e4a901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_control_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('employeeMemberId', sa.String(length=36), nullable=False),
    sa.Column('accessPoint', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('grantedByMemberId', sa.String(length=36), nullable=True),
    sa.Column('grantedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employeeMemberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grantedByMemberId'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('aca_member_idx', 'access_control_assignment', ['employeeMemberId'], unique=False)
    op.create_index('aca_member_point_idx', 'access_control_assignment', ['employeeMemberId', 'accessPoint'], unique=True)
    op.create_index('aca_org_idx', 'access_control_assignment', ['organizationId'], unique=False)
    op.create_index('aca_point_idx', 'access_control_assignment', ['accessPoint'], unique=False)
    op.create_index('aca_status_idx', 'access_control_assignment', ['status'], unique=False)
    op.create_table('access_control_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('employeeMemberId', sa.String(length=36), nullable=False),
    sa.Column('assetId', sa.String(length=36), nullable=True),
    sa.Column('accessPoint', sa.String(length=120), nullable=False),
    sa.Column('entryMethod', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('enteredAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assetId'], ['asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employeeMemberId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('acl_entered_at_idx', 'access_control_log', ['enteredAt'], unique=False)
    op.create_index('acl_member_idx', 'access_control_log', ['employeeMemberId'], unique=False)
    op.create_index('acl_org_idx', 'access_control_log', ['organizationId'], unique=False)
    op.create_index('acl_point_idx', 'access_control_log', ['accessPoint'], unique=False)
    op.create_index('acl_status_idx', 'access_control_log', ['status'], unique=False)
    op.drop_index(op.f('asset_maintenance_log_replacementDecision_idx'), table_name='asset_maintenance_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('asset_maintenance_log_replacementDecision_idx'), 'asset_maintenance_log', ['replacementDecision'], unique=False)
    op.drop_index('acl_status_idx', table_name='access_control_log')
    op.drop_index('acl_point_idx', table_name='access_control_log')
    op.drop_index('acl_org_idx', table_name='access_control_log')
    op.drop_index('acl_member_idx', table_name='access_control_log')
    op.drop_index('acl_entered_at_idx', table_name='access_control_log')
    op.drop_table('access_control_log')
    op.drop_index('aca_status_idx', table_name='access_control_assignment')
    op.drop_index('aca_point_idx', table_name='access_control_assignment')
    op.drop_index('aca_org_idx', table_name='access_control_assignment')
    op.drop_index('aca_member_point_idx', table_name='access_control_assignment')
    op.drop_index('aca_member_idx', table_name='access_control_assignment')
    op.drop_table('access_control_assignment')
    # ### end Alembic commands ###
