"""add requisition system

Revision ID: f41f4e7cb3c6
Revises: 3c3beaa89523
Create Date: 2026-05-07 23:44:34.957370
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41f4e7cb3c6'
down_revision: Union[str, None] = '3c3beaa89523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requisition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('departmentId', sa.String(length=36), nullable=True),
    sa.Column('employmentType', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employmenttype'), nullable=False),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('salaryMin', sa.Float(), nullable=True),
    sa.Column('salaryMax', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('isRemote', sa.Boolean(), nullable=False),
    sa.Column('raisedById', sa.String(length=36), nullable=False),
    sa.Column('targetDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CLOSED', name='jobrequisitionstatus'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['departmentId'], ['department.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raisedById'], ['member.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requisition_departmentId'), 'job_requisition', ['departmentId'], unique=False)
    op.create_index('ix_job_requisition_org_raised_by', 'job_requisition', ['organizationId', 'raisedById'], unique=False)
    op.create_index('ix_job_requisition_org_status', 'job_requisition', ['organizationId', 'status'], unique=False)
    op.create_index(op.f('ix_job_requisition_organizationId'), 'job_requisition', ['organizationId'], unique=False)
    op.create_index(op.f('ix_job_requisition_raisedById'), 'job_requisition', ['raisedById'], unique=False)
    op.create_index(op.f('ix_job_requisition_status'), 'job_requisition', ['status'], unique=False)
    op.create_table('requisition_approval',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organizationId', sa.String(length=36), nullable=False),
    sa.Column('requisitionId', sa.String(length=36), nullable=False),
    sa.Column('approverId', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requisitionapprovaldecision'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decidedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approverId'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisitionId'], ['job_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisitionId', 'approverId', name='uq_requisition_approval_requisition_approver')
    )
    op.create_index(op.f('ix_requisition_approval_approverId'), 'requisition_approval', ['approverId'], unique=False)
    op.create_index(op.f('ix_requisition_approval_decision'), 'requisition_approval', ['decision'], unique=False)
    op.create_index(op.f('ix_requisition_approval_organizationId'), 'requisition_approval', ['organizationId'], unique=False)
    op.create_index(op.f('ix_requisition_approval_requisitionId'), 'requisition_approval', ['requisitionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requisition_approval_requisitionId'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_organizationId'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_decision'), table_name='requisition_approval')
    op.drop_index(op.f('ix_requisition_approval_approverId'), table_name='requisition_approval')
    op.drop_table('requisition_approval')
    op.drop_index(op.f('ix_job_requisition_status'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_raisedById'), table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_organizationId'), table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_status', table_name='job_requisition')
    op.drop_index('ix_job_requisition_org_raised_by', table_name='job_requisition')
    op.drop_index(op.f('ix_job_requisition_departmentId'), table_name='job_requisition')
    op.drop_table('job_requisition')
    # ### end Alembic commands ###
