"""sync_schema_changes

Revision ID: f4c5c5b65399
Revises: 4b262fe191ed
Create Date: 2026-05-15 07:07:59.024605
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4c5c5b65399'
down_revision: Union[str, None] = '4b262fe191ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_reassignment_request_eventId'), table_name='interview_reassignment_request')
    op.drop_index(op.f('ix_interview_reassignment_request_organizationId'), table_name='interview_reassignment_request')
    op.drop_index(op.f('ix_interview_reassignment_request_requestedByMemberId'), table_name='interview_reassignment_request')
    op.drop_index(op.f('ix_interview_reassignment_request_resolvedByMemberId'), table_name='interview_reassignment_request')
    op.drop_index(op.f('ix_interview_reassignment_request_status'), table_name='interview_reassignment_request')
    op.drop_table('interview_reassignment_request')
    op.drop_index(op.f('asset_category_definition_id_idx'), table_name='asset')
    op.drop_index(op.f('asset_assignment_unit_idx'), table_name='asset_assignment')
    op.drop_column('asset_category_definition', 'asset_code')
    op.drop_index(op.f('asset_maintenance_log_unit_idx'), table_name='asset_maintenance_log')
    op.drop_index(op.f('ix_hiring_team_org_job'), table_name='hiring_team')
    op.drop_constraint(op.f('uq_hiring_team_job_posting_name'), 'hiring_team', type_='unique')
    op.create_index('hiring_team_jobPostingId_idx', 'hiring_team', ['jobPostingId'], unique=False)
    op.create_index('hiring_team_organizationId_idx', 'hiring_team', ['organizationId'], unique=False)
    op.create_index('hiring_team_organizationId_isActive_idx', 'hiring_team', ['organizationId', 'isActive'], unique=False)
    op.drop_index(op.f('ix_hiring_team_member_teamId'), table_name='hiring_team_member')
    op.drop_constraint(op.f('uq_hiring_team_member_team_member'), 'hiring_team_member', type_='unique')
    op.create_index(op.f('ix_hiring_team_member_hiringTeamId'), 'hiring_team_member', ['hiringTeamId'], unique=False)
    op.create_unique_constraint('uq_hiring_team_member', 'hiring_team_member', ['hiringTeamId', 'memberId'])
    op.drop_index(op.f('ix_pipeline_stage_org_slug'), table_name='pipeline_stage')
    op.drop_constraint(op.f('uq_pipeline_stage_org_slug'), 'pipeline_stage', type_='unique')
    op.create_unique_constraint('uq_pipeline_stage_job_slug', 'pipeline_stage', ['jobPostingId', 'slug'])
    op.add_column('stage_event', sa.Column('completedByMemberId', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_stage_event_assignedTeamId'), table_name='stage_event')
    op.drop_index(op.f('ix_stage_event_reassignedFromEventId'), table_name='stage_event')
    op.create_index(op.f('ix_stage_event_completedByMemberId'), 'stage_event', ['completedByMemberId'], unique=False)
    op.drop_constraint(op.f('fk_stage_event_assigned_team'), 'stage_event', type_='foreignkey')
    op.drop_constraint(op.f('fk_stage_event_reassigned_from_event'), 'stage_event', type_='foreignkey')
    op.create_foreign_key(None, 'stage_event', 'member', ['completedByMemberId'], ['id'], ondelete='SET NULL')
    op.drop_column('stage_event', 'reassignedFromEventId')
    op.drop_column('stage_event', 'assignmentStrategy')
    op.drop_column('stage_event', 'assignedTeamId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_event', sa.Column('assignedTeamId', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('stage_event', sa.Column('assignmentStrategy', postgresql.ENUM('ROUND_ROBIN', 'LEAST_LOADED', 'SKILL_MATCH', 'AVAILABILITY_FIRST', 'AI_BALANCED', name='assignmentstrategy'), autoincrement=False, nullable=True))
    op.add_column('stage_event', sa.Column('reassignedFromEventId', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stage_event', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stage_event_reassigned_from_event'), 'stage_event', 'stage_event', ['reassignedFromEventId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stage_event_assigned_team'), 'stage_event', 'hiring_team', ['assignedTeamId'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_stage_event_completedByMemberId'), table_name='stage_event')
    op.create_index(op.f('ix_stage_event_reassignedFromEventId'), 'stage_event', ['reassignedFromEventId'], unique=False)
    op.create_index(op.f('ix_stage_event_assignedTeamId'), 'stage_event', ['assignedTeamId'], unique=False)
    op.drop_column('stage_event', 'completedByMemberId')
    op.drop_constraint('uq_pipeline_stage_job_slug', 'pipeline_stage', type_='unique')
    op.create_unique_constraint(op.f('uq_pipeline_stage_org_slug'), 'pipeline_stage', ['organizationId', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipeline_stage_org_slug'), 'pipeline_stage', ['organizationId', 'slug'], unique=False)
    op.drop_constraint('uq_hiring_team_member', 'hiring_team_member', type_='unique')
    op.drop_index(op.f('ix_hiring_team_member_hiringTeamId'), table_name='hiring_team_member')
    op.create_unique_constraint(op.f('uq_hiring_team_member_team_member'), 'hiring_team_member', ['hiringTeamId', 'memberId'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_hiring_team_member_teamId'), 'hiring_team_member', ['hiringTeamId'], unique=False)
    op.drop_index('hiring_team_organizationId_isActive_idx', table_name='hiring_team')
    op.drop_index('hiring_team_organizationId_idx', table_name='hiring_team')
    op.drop_index('hiring_team_jobPostingId_idx', table_name='hiring_team')
    op.create_unique_constraint(op.f('uq_hiring_team_job_posting_name'), 'hiring_team', ['jobPostingId', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_hiring_team_org_job'), 'hiring_team', ['organizationId', 'jobPostingId'], unique=False)
    op.create_index(op.f('asset_maintenance_log_unit_idx'), 'asset_maintenance_log', ['assetUnitId'], unique=False)
    op.add_column('asset_category_definition', sa.Column('asset_code', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index(op.f('asset_assignment_unit_idx'), 'asset_assignment', ['assetUnitId'], unique=False)
    op.create_index(op.f('asset_category_definition_id_idx'), 'asset', ['categoryDefinitionId'], unique=False)
    op.create_table('interview_reassignment_request',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organizationId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('eventId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('requestedByMemberId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('reasonCode', postgresql.ENUM('OVERLOADED', 'UNAVAILABLE', 'CONFLICT', 'EMERGENCY', 'OTHER', name='reassignmentreasoncode'), autoincrement=False, nullable=False),
    sa.Column('reasonText', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'RESOLVED', 'DISMISSED', name='reassignmentrequeststatus'), server_default=sa.text("'OPEN'::reassignmentrequeststatus"), autoincrement=False, nullable=False),
    sa.Column('resolvedByMemberId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], name=op.f('interview_reassignment_request_eventId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], name=op.f('interview_reassignment_request_organizationId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestedByMemberId'], ['member.id'], name=op.f('interview_reassignment_request_requestedByMemberId_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolvedByMemberId'], ['member.id'], name=op.f('interview_reassignment_request_resolvedByMemberId_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_reassignment_request_pkey'))
    )
    op.create_index(op.f('ix_interview_reassignment_request_status'), 'interview_reassignment_request', ['status'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_resolvedByMemberId'), 'interview_reassignment_request', ['resolvedByMemberId'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_requestedByMemberId'), 'interview_reassignment_request', ['requestedByMemberId'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_organizationId'), 'interview_reassignment_request', ['organizationId'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_eventId'), 'interview_reassignment_request', ['eventId'], unique=False)
    # ### end Alembic commands ###
