"""sync_schema_changes

Revision ID: f4c5c5b65399
Revises: 4b262fe191ed
Create Date: 2026-05-15 07:07:59.024605
"""
# ruff: noqa: E501
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4c5c5b65399'
down_revision: Union[str, None] = '4b262fe191ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS "ix_interview_reassignment_request_eventId"')
    op.execute('DROP INDEX IF EXISTS "ix_interview_reassignment_request_organizationId"')
    op.execute('DROP INDEX IF EXISTS "ix_interview_reassignment_request_requestedByMemberId"')
    op.execute('DROP INDEX IF EXISTS "ix_interview_reassignment_request_resolvedByMemberId"')
    op.execute('DROP INDEX IF EXISTS "ix_interview_reassignment_request_status"')
    op.execute("DROP TABLE IF EXISTS interview_reassignment_request")
    op.execute("DROP INDEX IF EXISTS asset_category_definition_id_idx")
    op.execute("DROP INDEX IF EXISTS asset_assignment_unit_idx")
    op.execute('ALTER TABLE asset_category_definition DROP COLUMN IF EXISTS asset_code')
    op.execute("DROP INDEX IF EXISTS asset_maintenance_log_unit_idx")
    op.execute("DROP INDEX IF EXISTS ix_hiring_team_org_job")
    op.execute('ALTER TABLE hiring_team DROP CONSTRAINT IF EXISTS uq_hiring_team_job_posting_name')
    op.execute('CREATE INDEX IF NOT EXISTS "hiring_team_jobPostingId_idx" ON hiring_team ("jobPostingId")')
    op.execute('CREATE INDEX IF NOT EXISTS "hiring_team_organizationId_idx" ON hiring_team ("organizationId")')
    op.execute('CREATE INDEX IF NOT EXISTS "hiring_team_organizationId_isActive_idx" ON hiring_team ("organizationId", "isActive")')
    op.execute('DROP INDEX IF EXISTS "ix_hiring_team_member_teamId"')
    op.execute('ALTER TABLE hiring_team_member DROP CONSTRAINT IF EXISTS uq_hiring_team_member_team_member')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_hiring_team_member_hiringTeamId" ON hiring_team_member ("hiringTeamId")')
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_hiring_team_member'
            ) THEN
                ALTER TABLE hiring_team_member
                    ADD CONSTRAINT uq_hiring_team_member UNIQUE ("hiringTeamId", "memberId");
            END IF;
        END $$;
        """
    )
    op.execute("DROP INDEX IF EXISTS ix_pipeline_stage_org_slug")
    op.execute("ALTER TABLE pipeline_stage DROP CONSTRAINT IF EXISTS uq_pipeline_stage_org_slug")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'uq_pipeline_stage_job_slug'
            ) THEN
                ALTER TABLE pipeline_stage
                    ADD CONSTRAINT uq_pipeline_stage_job_slug UNIQUE ("jobPostingId", slug);
            END IF;
        END $$;
        """
    )
    op.execute('ALTER TABLE stage_event ADD COLUMN IF NOT EXISTS "completedByMemberId" VARCHAR(36)')
    op.execute('DROP INDEX IF EXISTS "ix_stage_event_assignedTeamId"')
    op.execute('DROP INDEX IF EXISTS "ix_stage_event_reassignedFromEventId"')
    op.execute('CREATE INDEX IF NOT EXISTS "ix_stage_event_completedByMemberId" ON stage_event ("completedByMemberId")')
    op.execute("ALTER TABLE stage_event DROP CONSTRAINT IF EXISTS fk_stage_event_assigned_team")
    op.execute("ALTER TABLE stage_event DROP CONSTRAINT IF EXISTS fk_stage_event_reassigned_from_event")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'stage_event'::regclass
                    AND confrelid = 'member'::regclass
                    AND conkey = ARRAY[
                        (
                            SELECT attnum
                            FROM pg_attribute
                            WHERE attrelid = 'stage_event'::regclass
                                AND attname = 'completedByMemberId'
                        )
                    ]::smallint[]
            ) THEN
                ALTER TABLE stage_event
                    ADD FOREIGN KEY ("completedByMemberId")
                    REFERENCES member (id)
                    ON DELETE SET NULL;
            END IF;
        END $$;
        """
    )
    op.execute('ALTER TABLE stage_event DROP COLUMN IF EXISTS "reassignedFromEventId"')
    op.execute('ALTER TABLE stage_event DROP COLUMN IF EXISTS "assignmentStrategy"')
    op.execute('ALTER TABLE stage_event DROP COLUMN IF EXISTS "assignedTeamId"')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_event', sa.Column('assignedTeamId', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('stage_event', sa.Column('assignmentStrategy', postgresql.ENUM('ROUND_ROBIN', 'LEAST_LOADED', 'SKILL_MATCH', 'AVAILABILITY_FIRST', 'AI_BALANCED', name='assignmentstrategy'), autoincrement=False, nullable=True))
    op.add_column('stage_event', sa.Column('reassignedFromEventId', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stage_event', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stage_event_reassigned_from_event'), 'stage_event', 'stage_event', ['reassignedFromEventId'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_stage_event_assigned_team'), 'stage_event', 'hiring_team', ['assignedTeamId'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_stage_event_completedByMemberId'), table_name='stage_event')
    op.create_index(op.f('ix_stage_event_reassignedFromEventId'), 'stage_event', ['reassignedFromEventId'], unique=False)
    op.create_index(op.f('ix_stage_event_assignedTeamId'), 'stage_event', ['assignedTeamId'], unique=False)
    op.drop_column('stage_event', 'completedByMemberId')
    op.drop_constraint('uq_pipeline_stage_job_slug', 'pipeline_stage', type_='unique')
    op.create_unique_constraint(op.f('uq_pipeline_stage_org_slug'), 'pipeline_stage', ['organizationId', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipeline_stage_org_slug'), 'pipeline_stage', ['organizationId', 'slug'], unique=False)
    op.drop_constraint('uq_hiring_team_member', 'hiring_team_member', type_='unique')
    op.drop_index(op.f('ix_hiring_team_member_hiringTeamId'), table_name='hiring_team_member')
    op.create_unique_constraint(op.f('uq_hiring_team_member_team_member'), 'hiring_team_member', ['hiringTeamId', 'memberId'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_hiring_team_member_teamId'), 'hiring_team_member', ['hiringTeamId'], unique=False)
    op.drop_index('hiring_team_organizationId_isActive_idx', table_name='hiring_team')
    op.drop_index('hiring_team_organizationId_idx', table_name='hiring_team')
    op.drop_index('hiring_team_jobPostingId_idx', table_name='hiring_team')
    op.create_unique_constraint(op.f('uq_hiring_team_job_posting_name'), 'hiring_team', ['jobPostingId', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_hiring_team_org_job'), 'hiring_team', ['organizationId', 'jobPostingId'], unique=False)
    op.create_index(op.f('asset_maintenance_log_unit_idx'), 'asset_maintenance_log', ['assetUnitId'], unique=False)
    op.add_column('asset_category_definition', sa.Column('asset_code', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index(op.f('asset_assignment_unit_idx'), 'asset_assignment', ['assetUnitId'], unique=False)
    op.create_index(op.f('asset_category_definition_id_idx'), 'asset', ['categoryDefinitionId'], unique=False)
    op.create_table('interview_reassignment_request',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organizationId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('eventId', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('requestedByMemberId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('reasonCode', postgresql.ENUM('OVERLOADED', 'UNAVAILABLE', 'CONFLICT', 'EMERGENCY', 'OTHER', name='reassignmentreasoncode'), autoincrement=False, nullable=False),
    sa.Column('reasonText', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('OPEN', 'RESOLVED', 'DISMISSED', name='reassignmentrequeststatus'), server_default=sa.text("'OPEN'::reassignmentrequeststatus"), autoincrement=False, nullable=False),
    sa.Column('resolvedByMemberId', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['stage_event.id'], name=op.f('interview_reassignment_request_eventId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizationId'], ['organization.id'], name=op.f('interview_reassignment_request_organizationId_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requestedByMemberId'], ['member.id'], name=op.f('interview_reassignment_request_requestedByMemberId_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolvedByMemberId'], ['member.id'], name=op.f('interview_reassignment_request_resolvedByMemberId_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_reassignment_request_pkey'))
    )
    op.create_index(op.f('ix_interview_reassignment_request_status'), 'interview_reassignment_request', ['status'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_resolvedByMemberId'), 'interview_reassignment_request', ['resolvedByMemberId'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_requestedByMemberId'), 'interview_reassignment_request', ['requestedByMemberId'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_organizationId'), 'interview_reassignment_request', ['organizationId'], unique=False)
    op.create_index(op.f('ix_interview_reassignment_request_eventId'), 'interview_reassignment_request', ['eventId'], unique=False)
    # ### end Alembic commands ###
